### ISSUE TITLE
OCSP Stapling on Apache

### ISSUE THREAD

**Issue by d--j** [mozilla/server-side-tls#1]
On https://github.com/mozilla/server-side-tls/blob/gh-pages/ssl-config-generator/index.html#L156
you add the `ssl_trusted_certificate` directive in the Apache directives. The `ssl_trusted_certificate` directive is for nginx not for Apache. Apache uses the `SSLCACertificateFile` that you already have included for OCSP Stapling response validation.

Looks like the `ssl_trusted_certificate` is missing in the nginx option. So probably you just added the line in the wrong block.

**Comment by gene1wood** [comment]
Thanks @d--j for catching that. Fixed now.
