### ISSUE TITLE
Optionally support Java6 at all time

### ISSUE THREAD

**Issue by atzezitman** [mozilla/server-side-tls#104]
The Generator might want to add 2 extra properties:
- "Support Java6" yes / no
- "Diffie-Hellman key used" 1024 / 2048 / 4096

We generated with Apache 2.2.15, Intermediate, OpenSSL 1.0.1e which provided the following Cipherlist:
...:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:...

But because we already use a 2048Diffie-Hellman key, Java6 was no longer supported. We resolved this by moving AES256-SHA and AES128-SHA, resulting in:
...:DHE-RSA-AES128-SHA256:AES256-SHA:AES128-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:...

We prefer AES256-SHA over AES128-SHA, because Forward Secrecy is not supported.

**Comment by tomato42** [comment]
I'd say that using 1024 bit DH with unique parameters (and regenerating them every few days, if you're really worried) is better than forgoing Forward Secrecy.

you are talking about targeted attack either way (be it somehow getting the RSA private key or cracking the unique DH parameters), in such situation, direct attack on the server is more likely, and then exfiltrating RSA private key is something they need to do just once, while access to DH params doesn't give them anything new

**Comment by april** [comment]
The new generator is aware of what you are doing with Java and DHE, and so does something very much like this.  :)
