### ISSUE TITLE
java 6 & 7 now support dhe 2048

### ISSUE THREAD

**Issue by jvehent** [mozilla/server-side-tls#107]
Received by email:

> From: Patrick Dunn <patrick.dunn@vdtg.com>
> To: <security@mozilla.org>
> Cc: 
> Date: Wed, 6 Jan 2016 15:41:45 -0700
> Subject: Recommended update to Server_Side_TLS page - JRE 6 & 7 support for 2048 DHE keys
> I found the the https://wiki.mozilla.org/Security/Server_Side_TLS extremely helpful.
> 
> The page mentions in a few places that Java6 and java 7 do not support DHE parameters >1024 (e.g., "DHE and ECDHE support", "DHE and Java", and app-specific guidance).
> 
> However, you may want to update it to reflect that Java 6 & 7 now support for DH ephemeral keys up to 2048 bits, starting with JRE 6U105 (aka1.6.0_105) and 7u91 (aka 1.7.0_91)/
> 
> References:
> Oracle Java SE 7 Advanced & Oracle Java SE 7 Support Release Notes (http://www.oracle.com/technetwork/java/javaseproducts/documentation/javase7supportreleasenotes-1601161.html)
> Oracle Java SE 6 Advanced & Oracle Java SE 6 Support Release Notes (http://www.oracle.com/technetwork/java/javase/documentation/overview-156328.html)

**Comment by tomato42** [comment]
Neither of which is available to general public.

For Java 7 it's 7u80:
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html
While for Java 6 it's 6u45:
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase6-419409.html

**Comment by madorb** [comment]
Just to be clear - the versions that @tomato42 posted DO NOT contain the fix for DHE > 1024 - they are just the last publicly available versions. The versions that DO contain DHE > 1024 are only available to oracle support subscribers.

**Comment by april** [comment]
I don't want to get too into the weeds for Java subversions, so the new generator just talks about Java 6 and Java 8 for Old and Intermediate. I think that's probably fine, and people still using ancient versions of Java with support contracts can figure out if they can handle DHE >=2048 bits.  :)

**Comment by wbsouza** [comment]
You may want to try Bouncy Castle implementations, I believe it works even with older Java versions.
Take a look on [this experiment](https://stackoverflow.com/questions/33364100/how-to-use-tls-1-2-in-java-6/61115302#61115302) that I made TLSv1.2 works by default using the JDK 1.6
