### ISSUE TITLE
TLS1.x support in RHEL6-based Apache

### ISSUE THREAD

**Issue by teridon** [mozilla/server-side-tls#110]
The generator currently does not allow the user to disable TLS versions (e.g. "SSLProtocol -all TLSv1.2"), despite that this is supported on RHEL6 versions of httpd/mod_ssl (after 2.2.15-31, see https://rhn.redhat.com/network/software/packages/change_log.pxt?pid=1080170 )

Perhaps add a pulldown for OS version?  If OS is RHEL6 variant, add appropriate TLS versions for SSLProtocol.

**Comment by jvehent** [comment]
I don't think we can reliably track distributions. We already attempt to track various web server and versions of openssl, and it's proving quite expensive. I'm afraid we'll have to leave that to the administrators.

**Comment by tomato42** [comment]
Then maybe adding a note that some distribution packages may have features backported from later releases?

**Comment by april** [comment]
Closing as this is a bit too much into the weeds for the generator, and I'm not sure it's really a problem anymore either.
