### ISSUE TITLE
Support for IIS

### ISSUE THREAD

**Issue by SidShaytay** [mozilla/server-side-tls#112]
Request support for cipher suite generation for IIS (newer: v8.5, v10). Here is a skeleton Powershell script to help you guys get started; please rename the .txt file to ps1. The key area to focus on would be the order of ciphersuites to keep them consistent with Mozilla recommendations.

[HardenSsl.ps1.txt](https://github.com/mozilla/server-side-tls/files/107689/HardenSsl.ps1.txt)

**Comment by jvehent** [comment]
Thanks Sid. One issue though: I have no idea how to review and integrate this because I've never used IIS. If someone wants to pick this  up and create a pull request, we'd welcome the help :)

**Comment by jrchamp** [comment]
Here's the IIS tool I've seen: https://www.nartac.com/Products/IISCrypto

**Comment by april** [comment]
If you'd be willing to generate a template and send a PR, I'd be happy to merge it here:
https://github.com/mozilla/ssl-config-generator

Thanks!
