### ISSUE TITLE
Add HTTP/2 support

### ISSUE THREAD

**Issue by Sp1l** [mozilla/server-side-tls#115]
The latest versions of Apache (as of 2.4.17) and Nginx (as of 1.9.5) both support HTTP/2.

It would be very helpful if appropriate configurations were added to the guide.

**Comment by szepeviktor** [comment]
> both support HTTP.

You mean HTTP/2.

**Comment by fruitl00p** [comment]
FYI, currently the nginx 1.9.5+ settings confirm the move to H2 (HTTP2)

**Comment by thomas-nilsson-irfu** [comment]
It might be a good idea mentioning somewhere on the wiki that some ciphers (which are presently found in the _intermediate compatibility_) are in fact [black listed](https://http2.github.io/http2-spec/#BadCipherSuites) in the http/2 and as such connections MAY fail when using http/2.

Among the black listed ciphers presently in the _intermediate_ are for instance DHE-RSA-AES128-SHA (openssl) aka. TLS_DHE_RSA_WITH_AES_128_CBC_SHA (IANA).

**Comment by floatingatoll** [comment]
Note that they are only blacklisted in conjunction with TLS 1.2.

Do any webservers implement this restriction in production in the wild today?

**Comment by lukastribus** [comment]
This is enforced by browsers, not webservers.

Look for ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY, e.g:
https://www.jeffgeerling.com/blog/2016/fixing-errspdyinadequatetransportsecurity-ssl-error-chrome

**Comment by floatingatoll** [comment]
Lukas: To clarify, this *is* enforced by clients, and *could be but is not*
enforced by webservers?

 - R.

**Comment by lukastribus** [comment]
It is.

Chrome will reject the HTTPS session and return ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY to the user.

edit: However the mozilla cipher configuration works fine by default with HTTP2. It does contain blacklisted ciphers like Thomas said, but they are de-prioritized so there really is no issue here. It may be useful to mentioned this somewhere, but cipher list works perfectly fine, when configured as per Mozilla's recommendation.

**Comment by april** [comment]
This has been working with nginx for a while, but now Apache also adds support in the config generator:

https://mozilla.github.io/ssl-config-generator/#server=apache&server-version=2.4.39&config=intermediate&openssl-version=1.1.1b&hsts=true&ocsp=true
