### ISSUE TITLE
F5 TLS Configuration out of date

### ISSUE THREAD

**Issue by boktai1000** [mozilla/server-side-tls#118]
Per the TLS_Configurations page:

"Currently DHE-RSA-AES128-SHA256 & DHE-RSA-AES256-SHA256 are not available in TMOS v11.6.x. This is expected to be resolved in an upcoming hotfix and the next major release of TMOS. The full list of support ciphers is available here: https://support.f5.com/kb/en-us/solutions/public/13000/100/sol13163.html"

It seems that 12.0 has been released, and the link provided shows those ciphers as present.

**Comment by gene1wood** [comment]
@boktai1000 can you add a bit more detail, does this relate to the TLS guidelines that we provide, to the config generator or to something else?

**Comment by boktai1000** [comment]
Hi @gene1wood - this is in regards to the https://wiki.mozilla.org/Security/Server_Side_TLS web page which used to offer guidance on F5 Cipher Suite configuration and was at one point pending the release of an F5 BIG-IP firmware update to provide more ciphers.

Upon reviewing the page again (it's been a bit) it seems that the F5 has been effectively removed from it.

I looked it up on the Web Archive and you can see from there what was previously included at one point: https://web.archive.org/web/20160208185434/https://wiki.mozilla.org/Security/Server_Side_TLS

There was an entire section for different load balancers / SSL termination points and included guidance for the F5 not just for cipher suite but also HSTS, OCSP Stapling, etc with sample code and examples given.

**Comment by april** [comment]
We no longer talk about this in the guidelines, as they were becoming out of date due to a lack of time and subject matter experts.
