### ISSUE TITLE
nginx template uses deprecated ssl directive

### ISSUE THREAD

**Issue by neitsab** [mozilla/server-side-tls#12]
Hi, thanks for this convenient tool and the associated wiki content, it really helped the novice webmaster I am to make his webserver more secure :-)

I noticed nginx' template uses the `ssl on;` directive ([line 41](https://github.com/mozilla/server-side-tls/blob/gh-pages/ssl-config-generator/index.html#L41)); notice however that [its documentation states](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl):

> It is recommended to use the `ssl` parameter of the [listen](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) directive instead of this directive. 

Its use is also recommend against on the [https servers configuration](http://nginx.org/en/docs/http/configuring_https_servers.html#single_http_https_server) page:

>  Prior to 0.7.14 SSL could not be enabled selectively for individual listening sockets, as shown above. SSL could only be enabled for the entire server using the [ssl](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl) directive, making it impossible to set up a single HTTP/HTTPS server. The `ssl` parameter of the [listen](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) directive was added to solve this issue. The use of the [ssl](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl) directive in modern versions is thus discouraged.

So I'd recommend replacing it with:

``` nginx
listen 443 ssl;
```

which is always one line saved ;-)

**Comment by jeffbryner** [comment]
Makes sense to me, wanna submit a pull request?

**Comment by neitsab** [comment]
Sure thing, I had wondered whether I should go straight with a PR or first report the issue. Give me an hour to finish something else.
Meanwhile, what about the wiki?

**Comment by jeffbryner** [comment]
Thanks! I'll update the wiki.

**Comment by neitsab** [comment]
Thank you, it's a pleasure to contribute to such a responsive upstream!

**Comment by jeffbryner** [comment]
Thanks for the contribution! Always welcome
