### ISSUE TITLE
Use hosted JSON guidelines in config generator

### ISSUE THREAD

**Issue by jvehent** [mozilla/server-side-tls#120]
Now that we have the [guidelines as JSON](https://github.com/mozilla/server-side-tls/blob/gh-pages/json/server-side-tls-conf-4.0.json), it would be great to use that in the configuration generator instead of the hardcoded values.
@gene1wood or @marumari : any chance one of you could use your mad JS skillz to integrate the JSON file?

**Comment by april** [comment]
I wouldn't mind making this a project.  Dunno if I'll be able to get to it soon, but maybe during the London work week if I'm at home?

**Comment by april** [comment]
The new generator does indeed use the hosted JSON guidelines.  :)
