### ISSUE TITLE
Add support for Citrix Netscaler

### ISSUE THREAD

**Issue by johnzimm** [mozilla/server-side-tls#122]
We are trying to offload our SSL on a Citrix Netscaler.  Was relying on this tool for generating well known cipher lists to Apache and would like to continue using on Netscaler.

**Comment by gene1wood** [comment]
@johnzimm If you've got access to a netscaler, would you be able to/open to putting together a PR that adds support for this config format?

**Comment by johnzimm** [comment]
Open to: yes
Able to: maybe?

I've got access to the Netscaler - fumbling through the documentation now.

**Comment by april** [comment]
I'm closing this, but if you're able to generate a template I would be happy to add it here:
https://github.com/mozilla/ssl-config-generator

Thanks!
