### ISSUE TITLE
CAMELLIA is not disabled

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/server-side-tls#125]
Both TLS observatory and cipherscan suggests

```
Changes needed to match the intermediate level:
* remove cipher DHE-RSA-CAMELLIA256-SHA
* remove cipher CAMELLIA256-SHA
* remove cipher DHE-RSA-CAMELLIA128-SHA
* remove cipher CAMELLIA128-SHA
```

For Apache 2.4.10 + OpenSSL 1.0.1k Generator sets `SSLCipherSuite` to

```
ECDHE-ECDSA-CHACHA20-POLY1305
ECDHE-RSA-CHACHA20-POLY1305
ECDHE-ECDSA-AES128-GCM-SHA256
ECDHE-RSA-AES128-GCM-SHA256
ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES256-GCM-SHA384
ECDHE-ECDSA-AES128-SHA256
ECDHE-RSA-AES128-SHA256
ECDHE-ECDSA-AES128-SHA
ECDHE-RSA-AES256-SHA384
ECDHE-RSA-AES128-SHA
ECDHE-ECDSA-AES256-SHA384
ECDHE-ECDSA-AES256-SHA
ECDHE-RSA-AES256-SHA
DHE-RSA-AES128-SHA256
DHE-RSA-AES128-SHA
DHE-RSA-AES256-SHA256
DHE-RSA-AES256-SHA
ECDHE-ECDSA-DES-CBC3-SHA
ECDHE-RSA-DES-CBC3-SHA
EDH-RSA-DES-CBC3-SHA
AES128-GCM-SHA256
AES256-GCM-SHA384
AES128-SHA256
AES256-SHA256
AES128-SHA
AES256-SHA
DES-CBC3-SHA
!DSS
```

On Debian jessie.
Related #121

**Comment by szepeviktor** [comment]
These are the [Debian jessie CONFARGS](https://packages.debian.org/jessie/openssl)
`CONFARGS  = --prefix=/usr --openssldir=/usr/lib/ssl --libdir=lib/$(DEB_HOST_MULTIARCH) no-idea no-mdc2 no-rc5 no-zlib  enable-tlsext no-ssl2 no-ssl3`

Maybe adding `!CAMELLIA`?

**Comment by szepeviktor** [comment]
Anyone?

**Comment by jrchamp** [comment]
If the goal is to meet those recommendations, I'd probably just remove the CAMELLIA+SHA ones.

**Comment by szepeviktor** [comment]
The point is I don't mention CAMELLIA in the config file.

**Comment by szepeviktor** [comment]
Could we get `!CAMELLIA` into server-side-tls?

**Comment by jrchamp** [comment]
Camellia was removed by commit d255367a7de1f7324cdd2a3417c97bf1db4bd7ce ; if it's still showing up in your scans, you might want to update your configuration and restart Apache.

**Comment by szepeviktor** [comment]
Thank you.
I am trying to point out that in Debian CAMELLIA is enabled by default.

**Comment by jrchamp** [comment]
I'm running Debian. If you specify the SSLCipherSuite to the value provided by server-side-tls, it overrides the default. I have tested this on my system. Make sure your `/etc/apache2/mods-available/ssl.conf` is not overwriting your settings.

**Comment by szepeviktor** [comment]
Thank you very much!
Actually I configure Apache in mod_ssl's ssl.conf.

I must have overlooked something. Excuse me.

```
./analyze.py -t onlinemunkaido.hu
onlinemunkaido.hu:443 has intermediate ssl/tls

Changes needed to match the old level:
* enable SSLv3
* use a certificate with sha1WithRSAEncryption signature
* use DHE of 1024bits and ECC of 160bits

Changes needed to match the modern level:
* remove cipher DHE-RSA-AES128-GCM-SHA256
* remove cipher DHE-RSA-AES256-GCM-SHA384
* remove cipher ECDHE-RSA-AES128-SHA
* remove cipher ECDHE-RSA-AES256-SHA
* remove cipher DHE-RSA-AES128-SHA256
* remove cipher DHE-RSA-AES128-SHA
* remove cipher DHE-RSA-AES256-SHA256
* remove cipher DHE-RSA-AES256-SHA
* remove cipher ECDHE-RSA-DES-CBC3-SHA
* remove cipher EDH-RSA-DES-CBC3-SHA
* remove cipher AES128-GCM-SHA256
* remove cipher AES256-GCM-SHA384
* remove cipher AES128-SHA256
* remove cipher AES256-SHA256
* remove cipher AES128-SHA
* remove cipher AES256-SHA
* remove cipher DES-CBC3-SHA
* disable TLSv1.1
* disable TLSv1
```
