### ISSUE TITLE
Profile for ancient Apache broken

### ISSUE THREAD

**Issue by tun0** [mozilla/server-side-tls#127]
https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.0.52&openssl=0.9.7a&hsts=yes&profile=intermediate

The above URL lists the SSLHonorCipherOrder setting, but that isn't supported yet in Apache 2.0.52, as it got introduced in 2.0.65 according to http://httpd.apache.org/docs/2.0/mod/mod_ssl.html#sslhonorcipherorder.

**Comment by april** [comment]
Closing this because Apache 2.0 is long, long unsupported.  :)

**Comment by gene1wood** [comment]
Last release of Apache 2.0 was in [2013](http://mail-archives.apache.org/mod_mbox/httpd-announce/201307.mbox/%3C20130710124920.2b8793ed.wrowe%40rowe-clan.net%3E)
