### ISSUE TITLE
Modern haproxy conf is broken

### ISSUE THREAD

**Issue by danieljakots** [mozilla/server-side-tls#128]
Hi,

It seems it comes from 332cb015935b08cf386002dbeadfda4133c99836 from @Yajo 

Are you sure {{sslProtocols}} is needed? I get in the generator:
ssl-default-bind-options ssl no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
and then:
[ALERT] 062/190600 (6991) : parsing [/etc/haproxy/haproxy.cfg:12] : unknown option 'ssl' on global statement 'ssl-default-server-options'.
It's the same with ssl-default-bind-options.

FWIW, I'm running haproxy-1.5.14

**Comment by yajo** [comment]
Thanks, my mistake. Fixed in #129.
