### ISSUE TITLE
Generator: Java's SSLServerSocket

### ISSUE THREAD

**Issue by tomfitzhenry** [mozilla/server-side-tls#131]
I'm configuring a Java SSL service. It'd be nice to have guidance on the wiki/generator on how to do this, re Old/Intermediate/Modern.

I'm talking things like:
- SSLServerSocket.setEnabledProtocols
- SSLServerSocket.setEnabledCipherSuite
- How to enable OSCP/CRL
- ...

**Comment by gene1wood** [comment]
Yes, a PR is welcome for a new generator for Java SSL

**Comment by april** [comment]
If you'd like to open up a PR here, I'd be happy to take a look at it. Thanks!

https://github.com/mozilla/ssl-config-generator
