### ISSUE TITLE
Use of `SSLCACertificateFile` not very clear

### ISSUE THREAD

**Issue by osirisinferi** [mozilla/server-side-tls#132]
Hi guys,

If you search on Google for `SSLCACertificateFile`, you'll get many, _many_ results where `SSLCACertificateFile` is abused for sending a intermediate certificate.

If we look at the [docs](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcacertificatefile) however, it is _clearly_ stated `SSLCACertificateFile` is used for **client authentication**.

Furthermore, if someone would interpret this as it should contain _all_ CA certificates (for example, `/etc/ssl/certs/`) and one would leave `SSLCADNRequestFile` or `SSLCADNRequestPath` empty ánd would set up client authentication somewhere, the server will send _all_ CA names to the client.

That can't be proper behaviour.

My suggestion is to add a comment above `SSLCACertificateFile` mentioning the fact it should only be used for _client authentication purposes_.

**Comment by jrchamp** [comment]
It seems like [`SSLCertificateChainFile`](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcertificatechainfile) was the no-side-effects way to do this prior to 2.4.8. It still works for now, but is deprecated and generates a warning.

The docs do state that the use of `SSLCACertificatePath` (and it seems, by extension, `SSLCACertificateFile`) can be used as an alternative to `SSLCertificateChainFile`. In one sense, there is the added benefit (side-effect) that Client Authentication can also be performed (or required by .htaccess) without additional configuration changes. `SSLCACertificatePath` may be the better option if it avoids the "all CA names" issue you mentioned.

**Comment by osirisinferi** [comment]
`SSLCertificateChainFile` is deprecated indeed, but `SSLCACertificateFile` shouldn't be used in stead. Since 2.4.8 the option exists to feed a concatenation of the leaf and intermediate certificate to `SSLCertificateFile`.

And yes, although `SSLCACertificateFile` _could_ be used as an alternative to `SSLCertificateChainFile`, those same docs say you _should_ use the latter.

**Comment by jrchamp** [comment]
Does `SSLCACertificatePath` avoid the `SSLCADNRequestFile`/`SSLCADNRequestPath` empty issue where the server sends all CA names?

**Comment by osirisinferi** [comment]
`SSLCACertificatePath` _causes_ that problem. Putting just one certificate in `SSLCACertificateFile` isn't as bad, because it'll only send thát CA's name.

But my point was: `SSLCACertificateFile` (or Path) is used for _client authentication_. The fact it can also be used to send the intermediate certificate is just incidental. For Apache <2.4.8 there was `SSLCertificateChainFile` to do that and =>2.4.8 you can concatenate the leaf and intermediate into one file and use `SSLCertificateFile`. In any way, if the user doesn't want/need client authentication, `SSLCACertificate*` shouldn't be used.
But when you'd search on the web, you'd see everyone abusing `SSLCACertificateFile` just for that reason: sending the intermediate cert. Therefore, I'd think a comment in the generator would be nice.

See: https://www.google.com/search?q=apache+intermediate+certificate

The first site I get, from GlobalSign, is correct.. But the next few:

(&hellip;) [Locate the line "SSLCACertificateFile". Example:](https://access.redhat.com/solutions/43575) (&hellip;)

(&hellip;) [If the SSLCertificateChainFile directive does not work, try using the SSLCACertificateFile directive instead.](https://www.digicert.com/ssl-certificate-installation-apache.htm) (&hellip;)

(&hellip;) [SSLCACertificateFile /usr/local/ssl/crt/cabundle.crt](https://search.thawte.com/support/ssl-digital-certificates/index?page=content&id=SO15464) (&hellip;)

:sob:

**Comment by jrchamp** [comment]
Thank you for the clarification. I agree that modifications are needed in order to avoid relying on side effects for essential functionality. I propose the use of `SSLCertificateChainFile` for Apache prior to 2.4.8 and a note about appending the chain certificates to the `SSLCertificateFile` for Apache >= 2.4.8

**Comment by osirisinferi** [comment]
Well, other than a note (at the moment the use of `SSLCertificateFile`in Apache >=2.4.8 is clarified by the file name) for `SSLCertificateFile`, this is actually the current situation. But in addition to that, `SSLCACertificate` is _also_ specified. Which, of course, in the case of client authentication is 100% valid. But I'm not sure everyone on the world wide web fully understands the purpose of `SSLCACertificateFile`. Thát's what I'm worried about :wink:

**Comment by jrchamp** [comment]
Sorry, you are correct. I did not see the "{{certFile}}" logic.
