### ISSUE TITLE
CHACHA order

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/server-side-tls#136]
I've just noticed that CHACHA is not the first in "Modern" ciphers, but it is in "Old"' and " Intermediate".
Is it intentional?

https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.18&openssl=1.0.1k&hsts=yes&profile=modern

**Comment by rugk** [comment]
I'm also surprised by this fact. Especially as the CHACHA20-POLY1305 cipher is really new. E.g. only  [Firefox >= 47.0](https://www.mozilla.org/en-US/firefox/47.0/releasenotes/) supports it.

**Comment by szepeviktor** [comment]
@jvehent Could we make CHACHA-POLY first?

**Comment by tomato42** [comment]
No, the order is for servers, and most servers have hardware acceleration for AES-GCM, thus putting Chacha20 before AES-GCM would have a detrimental effect.

**Comment by szepeviktor** [comment]
> most servers have hardware acceleration for AES-GCM

Thank you.

**Comment by jvehent** [comment]
Hubert is obviously correct. In addition, the rationales sections on the
wiki page contains some extra details to help you understand the ordering.

**Comment by szepeviktor** [comment]
Here: https://github.com/mozilla/server-side-tls/blob/gh-pages/Server_Side_TLS.mediawiki#modern-compatibility

**Comment by rugk** [comment]
So how can one get out if the server supports AESNI? For fine-tuning the configuration...

**Comment by jvehent** [comment]
Look at the cpu flags in /proc/cpuinfo. If you see `aes` in there, your cpu supports aesni instructions.

**Comment by szepeviktor** [comment]
In bash:

``` bash
# Explain Intel CPU flags
wget https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/plain/arch/x86/include/asm/cpufeatures.h
for FLAG in $(grep -m1 "^flags" /proc/cpuinfo|cut -d":" -f2-); do
 echo -n "$FLAG"
 grep -C1 "^#define X86_\(FEATURE\|BUG\)_" cpufeatures.h \
 | grep -i -m1 "/\* \"${FLAG}\"\|^#define X86_\(FEATURE\|BUG\)_${FLAG}" \
 | grep -o './\*.*\*/' || echo "N/A"
done
```

**Comment by rugk** [comment]
@szepeviktor A bit complicated if you compare it to the other solution, is not it? :smiley:

**Comment by szepeviktor** [comment]
Could be. But one may understand the flags this way.
_I did._
