### ISSUE TITLE
Multiple issues with nginx (mainline) version while using the generator

### ISSUE THREAD

**Issue by ItsAdventureTime** [mozilla/server-side-tls#139]
An error will be generated in **nginx** `shared memory zone "SSL" conflicts with already declared size...` because of the `ssl_session_cache` already set in `/etc/nginx/nginx.conf`. The `ssl_session_cache` must be removed in that configuration. _(Ref: http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_session_cache and https://github.com/letsencrypt/letsencrypt/issues/921)_. The use of `builtin:1000` causes memory fragmentation.

The module `ssl_trusted_certificates` does not exist in **nginx**, it should be `ssl_trusted_certificate`. _(Ref: http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_trusted_certificate)_

Here is what I have generated: _https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-1.9.5&openssl=1.0.1e&hsts=yes&profile=modern_

**Comment by april** [comment]
These are both fixed in the latest version of the certificate generator:

https://mozilla.github.io/ssl-config-generator/

The memory zone thing is fixed by using a custom name; this is similar to what certbot does.
