### ISSUE TITLE
Serve over HTTPS

### ISSUE THREAD

**Issue by lgarron** [mozilla/server-side-tls#14]
If you're helping people generate server configs, you probably want to make sure that nobody is tampering with the code that generates them. (They're effectively permanent...)

Since github.io support HTTPS, https://mozilla.github.io/server-side-tls/ssl-config-generator/ functions perfectly.

At the very least, I think the link at https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_Server_Configurations should be updated to HTTPS.

While [it appears](https://github.com/isaacs/github/issues/156) that there isn't straightforward support for immediate redirects/HSTS yet, it might be good to do a [client-side redirect for now](https://gist.github.com/konklone/9968713). That way, anyone who bookmarks or copies the URL (while on an uncompromised connection) is going to have the secure link.

(I'd also suggest a warning not to use the tool over plain HTTP, but no one will read and heed that. A client-side redirect should hopefully eliminate the need for it.)

**Comment by jeffbryner** [comment]
Ha, good point. Updated the link. I'll leave the client-side redirect suggestion to the Gene (he's out of office at the moment.).

**Comment by lgarron** [comment]
Also just noticed the project link on GitHub.

![screen shot 2014-11-17 at 12 46 10](https://cloud.githubusercontent.com/assets/248078/5077394/ba24c7c6-6e57-11e4-9854-0058e352e12c.png)

**Comment by gene1wood** [comment]
I've updated the project link.

**Comment by gene1wood** [comment]
@lgarron Thanks for the suggestion of https only. Should work better now.
