### ISSUE TITLE
SSLProtocol flag for -SSLv2 missing when choosing OpenSSL 1.0.1e

### ISSUE THREAD

**Issue by tobiasehlert** [mozilla/server-side-tls#140]
When choosing OpenSSL version 1.0.1e with any other combination, the -SSLv2 flag on SSLProtocol is missing. This is a high risk for web servers since SSLv2 is very insecure!

The config should be:

```
SSLProtocol             all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
```

**Comment by netsnipe** [comment]
SSL v2 is no longer supported by mod_ssl in Apache 2.4 according to [this](https://httpd.apache.org/docs/current/mod/mod_ssl.html), so I'm guessing "-SSLv2" only needs to be explicitly declared for Apache 2.2 configurations.

**Comment by april** [comment]
Yep, it was also removed from OpenSSL builds unless you go out of your way to explicitly enable it.
