### ISSUE TITLE
 Server Side TLS suggestions for improvement

### ISSUE THREAD

**Issue by ghost** [mozilla/server-side-tls#142]
This is my recommendation for changes to the Server Side TLS recommendations on https://wiki.mozilla.org/Security/Server_Side_TLS . I performed rigorous compatibility testing on the following. Everything works as advertized. Please ask me if you have any questions, or let me know when you'll be available for discussion on the #security channel on Mozilla IRC server.

Modern:
ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256

Reasoning:
1) Too many people put 256bit CBC cipher suits at higher priority than 128bit AEAD cipher suits because they don't know what they are doing.
2) 256bit GCM cipher suits are not supported well.
3) 256bit AES cipher suits have issues that are not well studied yet that possibly make them weaker than 128bit cipher suits.
4) Only AEAD cipher suits can be considered modern.
5) Do not use DHE cipher suits because they are far too often implemented wrong (small DH sizes).

Intermediate:
ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA

Reasoning:
1) Start with Modern, then add others.
2) Add CBC cipher suits.
3) Add SHA1 cipher suits.
4) Add RSA cipher suits.
5) Do not use DHE cipher suits because they are far too often implemented wrong (small DH sizes).
6) Do not add any DES suits because we claim that Intermediate does not care about compatibility with Windows XP.

Old backward compatibility:
ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:DES-CBC3-SHA

Reasoning:
1) Start with Intermediate.
2) Add the missing DES ciphersuit that gives compatibility with old clients, such as Windows XP.
3) Nobody used SEED as the only supported ciphersuit.
4) Nobody used IDEA as the only supported ciphersuit.
5) Nobody used DSS as the only supported ciphersuit.
6) Nobody used Camellia as the only supported ciphersuit.
7) Really avoid DHE because of issues, and additionally performance issues for old-backwards compatible clients.

I especially implore you to change the old-backwards compatibility suites to the ones I stated, because far too many people just go ahead with old-backwards because they do not understand things.

Overall, this once again limits the number of ciphersuits in the wild, and makes it easier to remove supported weak ciphersuits from client applications.

**Comment by jvehent** [comment]
My experience dealing with ciphersuites compatibility is there are more clients with very odd ciphersuites support on the internet than most realize. 99.9% of support may be enough for a common site, but that 0.1% will hurt very specific populations we may care about.

The only way we're reducing the ciphersuites from the old and intermediate configuration is if:
- There is a vulnerability in one of the ciphersuites and we need to remove it
- Someone presents actual telemetry of usage that allows us to measure the impact of removing a ciphersuite. Of course, basing such telemetry on web browsers alone is not enough, since the problematic devices we're talking about here are _not_ browsers.

**Comment by april** [comment]
This has been addressed in 5.0.
