### ISSUE TITLE
Enable the new GitHub pages "Enforce HTTPS" option

### ISSUE THREAD

**Issue by edmorley** [mozilla/server-side-tls#144]
See:
https://help.github.com/articles/securing-your-github-pages-site-with-https/

Thanks :-)

**Comment by jvehent** [comment]
It's done automatically by github.

**Comment by edmorley** [comment]
I'm not sure I follow?

This is a new feature that wasn't supported by GitHub until today. Existing github pages need the option enabling (only newly created gh-pages sites will have it enabled by default), hence filing this issue :-)

**Comment by gene1wood** [comment]
@edmorley I've confirmed that the setting is currently checked (I didn't check it).

**Comment by jvehent** [comment]
I checked it. But even unchecked, I get redirected to HTTPS. Not sure why, since there is no HSTS, but that's what the server does.

**Comment by edmorley** [comment]
> I checked it. But even unchecked, I get redirected to HTTPS. Not sure why, since there is no HSTS, but that's what the server does.

That's the client-side redirect, which can now be removed (see #14).

**Comment by edmorley** [comment]
I've opened #145 to remove the client-side redirect.

**Comment by jvehent** [comment]
Awesome! Thanks!
