### ISSUE TITLE
no nginx-1.10 support

### ISSUE THREAD

**Issue by HalisCz** [mozilla/server-side-tls#146]
There is no support for current stable nginx version (1.10 according to [nginx PPA archive](https://launchpad.net/~nginx/+archive/ubuntu/stable/+packages))

**Comment by nbibler** [comment]
"No support," I'm guessing means it doesn't auto-fill with the current version of nginx in the text field?

I believe the configuration that's currently generated for nginx correctly works with and configures nginx 1.10. I haven't seen any issues with it in production.

Are you seeing differently?

**Comment by ghost** [comment]
Now we have nginx 1.11.3 - http://nginx.org/en/CHANGES :-)

**Comment by HalisCz** [comment]
> I believe the configuration that's currently generated for nginx correctly works with and configures nginx 1.10. I haven't seen any issues with it in production.
> 
> Are you seeing differently?

To be honest, I didn't try.

**Comment by april** [comment]
Yeah, I think this is just a comment thing; there haven't been any changes in the nginx conf in some time that would affect the functioning of the actual configuration.

**Comment by april** [comment]
The new version of the generator doesn't keep up to date with software versions, due to this issue:
https://mozilla.github.io/ssl-config-generator/
