### ISSUE TITLE
Modern configuration generator still points to DH param files

### ISSUE THREAD

**Issue by april** [mozilla/server-side-tls#148]
Even though the modern configuration uses only ECDHE, for some generators, it still points to a dhparam file, even thought it isn't needed.  Those lines should probably be omitted.

**Comment by FlorentATo** [comment]
I was about to report the same issue.
Not sure it worth opening a ticket but it might be useful to specify the curve used for ECC ciphers i.e. `ssl_ecdh_curve secp384r1;` (nginx).

Edit: The [wiki](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) is correct about this:
`DH Parameter size: None (disabled entirely)`

**Comment by gene1wood** [comment]
Duplicate of #123
