### ISSUE TITLE
Modern preset: SSLSessionTickets

### ISSUE THREAD

**Issue by mtimyself** [mozilla/server-side-tls#149]
I have selected apache 2.4.10 and then chosen the "modern preset".
When trying to restart apache I get an error with the line "SSLSessionTickets       off".
A quick google search has revealed that this setting is only available on apache 2.4.11 (or 2.4.12, people were not certain).
Commenting out this line resolved the issue.
I don't know if this is "intended", just thought I would let you know.

**Comment by meineerde** [comment]
The configuration generator already [checks](https://github.com/mozilla/server-side-tls/blob/832746e6658b7da5434a785f74172ce15fa85f77/ssl-config-generator/index.html#L369-L373) the Apache version before adding the `SSLSessionTickets off` option. It is only added for Apache >=2.4.11 or >=2.2.30 when using at least OpenSSL 0.9.8f.

**Comment by TekkCraft** [comment]
I agree with @meineerde .
This seems to be fixed.
