### ISSUE TITLE
If mod_headers is not enabled, make HSTS optional

### ISSUE THREAD

**Issue by dol** [mozilla/server-side-tls#15]
In some setups, mod_headers is not loaded. This helps preventing this problem.

```
<IfModule mod_headers.c>
    # HSTS
    Header add Strict-Transport-Security "max-age=15768000"
</IfModule>
```

**Comment by lgarron** [comment]
This would cause a silent failure if mod_headers.c is disabled, or if you migrate to a system that doesn't have it. It would appear that everything is still fine (and HSTS would even continue to work for past visitors until it expires!), but the security of the site would drop substantially.

HSTS is all about hard failures on the client side, and we should encourage similar diligence on the server side. Better to cause annoying errors than to cause surprises for people who _thought_ they were secure. (I'm usually a fan of making things "just work", but you have to be careful with security. And if someone is deploying HSTS, they need to know a bit about what they're getting themselves into.)

I think the line should be included unconditionally if the HSTS checkbox is checked. What about modifying the comment line to clarify its dependency?

```
# HSTS (this requires mod_headers)
Header add Strict-Transport-Security "max-age=15768000"
```

**Comment by dol** [comment]
I agree that's a error is better than drop security if mod_headers is not enabled.
I'm totally ok with the improvement to add a note about mod_headers. If the comment line is changed, it would be very helpful adding the time interval information as human readable comment =>15768000 seconds are 1/2 of a year

**Comment by gene1wood** [comment]
@dol @lgarron Thanks for the suggestions on this, good ideas.
