### ISSUE TITLE
Support OpenSSL 1.1.0

### ISSUE THREAD

**Issue by jtl999** [mozilla/server-side-tls#158]
https://www.openssl.org/news/openssl-1.1.0-notes.html

**Comment by FabioPedretti** [comment]
It is supported now...

**Comment by floatingatoll** [comment]
@jtl999, can you indicate where you came across an SSL configuration where you specified OpenSSL 1.1.0 but it gave you an invalid config? Or, were you unable to select OpenSSL 1.1.0 in the tool itself?
