### ISSUE TITLE
Curve usage

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/server-side-tls#162]
There is a `tls_curves` filed in the JSON data.

Should we set some configurations like "[SSLOpenSSLConfCmd Curves](https://www.openssl.org/docs/man1.0.2/ssl/SSL_CONF_cmd.html#SUPPORTED-CONFIGURATION-FILE-COMMANDS) secp521r1:secp384r1:prime256v1" in Apache? Is it necessary?

**Comment by szepeviktor** [comment]
[Apache doc](https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslopensslconfcmd) has an example:
`SSLOpenSSLConfCmd ECDHParameters brainpoolP256r1`

**Comment by tomato42** [comment]
for Apache there are two general options, named curve or automatic mode

So Apache with OpenSSL 1.0.2 can be only configured to support one curve or to automatically select the curve from the mutually supported ones. The downside is that unless you're running OpenSSL with Fedora-like patches that will enable also weak curves smaller than 256 bits.

**Comment by szepeviktor** [comment]
Thank you.

> will enable also weak curves

Do you mean when configured to use automatic **or** when configured to one curve?

**Comment by tomato42** [comment]
when configured to auto

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
> Apache with OpenSSL 1.0.2 can be only configured to support one curve

Could you help me a bit more and name your source as all I can find on the net is a colon-separated list of curve**s**.

**Comment by tomato42** [comment]
the same site you cited:

> Curves
> 
>    This sets the supported elliptic curves. For clients the curves are sent using the supported
>    curves extension. For servers it is used to determine which curve to use.

note the singular for server

For the client side you can configure openssl to support multiple arbitrary curves, for server side the settings are not so flexible
