### ISSUE TITLE
Confusing rationale

### ISSUE THREAD

**Issue by ekr** [mozilla/server-side-tls#163]
This text says:
"ChaCha20 is prefered as the fastest and safest in-software cipher, followed but AES128. Unlike the modern configuration, we do not assume clients support AESNI and thus do not prioritize AES256 above 128 and ChaCha20. There has been discussions (1, 2) on whether AES256 extra security was worth its computing cost in software (without AESNI), and the results are far from obvious. At the moment, AES128 is preferred, because it provides good security, is really fast, and seems to be more resistant to timing attacks."
1. AES-NI is much better for the server and therefore should be preferred to ChaCha (the server's performance needs are more important than the clients).
2. What's your citation for AES-128 being better for timing analysis than AES-256?

**Comment by april** [comment]
AES-128 vs. AES-256 has been talked about in #25, #32, #34, #35, and #72. It's definitely a complex discussion.

Can you explain why you believe the server's performance needs are much more important than the clients?  AES-NI is supported on pretty much every server, and ChaCha20 is extremely fast, so rarely is symmetric crypto a [significant performance problem](https://istlsfastyet.com/) on servers anymore.

On the other hand, there are many clients out there without accelerated AES; particularly smartphones and low-end laptops. Only modern Snapdragons (and of course Apple's Ax CPU series) have AES acceleration. And while you can always add more servers, you can't add more battery life or CPU power to the billions low-end cell phones in existence.

**Comment by ekr** [comment]
> AES-128 vs. AES-256 has been talked about in #25, #32, #34, #35, and #72. It's definitely a complex discussion

The question of whether to favor 256 or 128 is a complex discussion and I'm fine with favoring AES-128 (this is also what Firefox does). My question was what your source was for the timing analysis claim. Do you have one?

WRT to AES versus ChaCha: adding more servers costs money, and a large fraction of clients do in fact have accelerated AES (because they are desktop machines with Intel processors). The right thing to do is probably for the server to respect the client's preferences in this matter (IIRC, Chrome has a different pref list on mobile and desktop for this reason). If you have a stack which can't do that (which perhaps OpenSSL cannot) then the right thing to do is to look at what the bulk of your clients are like and make a judgement based on that.

**Comment by jvehent** [comment]
> The question of whether to favor 256 or 128 is a complex discussion and I'm fine with favoring AES-128 (this is also what Firefox does). My question was what your source was for the timing analysis claim. Do you have one?

During the [discussion](http://www.mail-archive.com/dev-tech-crypto@lists.mozilla.org/msg11325.html) we had back in 2013, the worry was that software implementations of AES-256 were more vulnerable to timing attacks than the 128 bits version.
- https://www.schneier.com/blog/archives/2009/07/new_attack_on_a.html
- https://eprint.iacr.org/2007/318.pdf

The reason AES-128 is preferred is a mix of these worries, added computational cost when AES-NI isn't supported, and unclear security benefit of doubling the key size.

The situation has changed over the last 3 years, and the Modern level prioritizes AES-256 to reflect the fact modern clients support AES-NI and get fast, constant time, AES. But we kept AES-128 prioritized in the Intermediate level assuming the population of client stuck in software AES would be greater there.

**Comment by april** [comment]
> The right thing to do is probably for the server to respect the client's preferences in this matter (IIRC, Chrome has a different pref list on mobile and desktop for this reason). If you have a stack which can't do that (which perhaps OpenSSL cannot) then the right thing to do is to look at what the bulk of your clients are like and make a judgement based on that.

That's essentially what setting ChaCha20 first does.  AFAIK, every significant client (aka Chrome) that supports ChaCha20 sets it as their first cipher. Having ChaCha20 first in the list accomplishes that, while also sticking with our recommendation to have the server select the cipher and not the client.

**Comment by april** [comment]
It is perhaps a miswording that we say "timing attack" instead of "related-key attack"?

**Comment by ekr** [comment]
Well, timing attacks and related key attacks are different, so probably it's important to talk about the right attack.

WRT cipher suite order, several points:
1. The desktop browsers with which I am familiar with do _not_ set ChaCha first. Chrome (release) has the following order:

"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)   Forward Secrecy 128
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   Forward Secrecy    128
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)   Forward Secrecy  256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   Forward Secrecy    256
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)   Forward Secrecy    256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)   Forward Secrecy  256
OLD_TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcc14)   Forward Secrecy    256
OLD_TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcc13)   Forward Secrecy"

Firefox Nightly has the following order:
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)   Forward Secrecy  128
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   Forward Secrecy    128
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)   Forward Secrecy    256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)   Forward Secrecy  256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)   Forward Secrecy  256

I don't have a copy of Chrome Android available, but I believe it prefers ChaCha.

WRT to the selection algorithm: the two common selection algorithms are either:

(1) prefer the highest ranked client cipher that the server supports
(2) prefer the highest ranked server cipher that the client supports

Note that the second is indifferent to client order, so you really want something more sophisticated which generally respects the server's preferences but treats ChaCha and AES as equipreferred. Have you verified that when configured as we recommend OpenSSL switch-hits between ChaCha and AES depending on client preference?

**Comment by april** [comment]
A lot of this discussion has been removed from 5.0 and most configurations support client choice, eliminating the need to really go into the rationale of AES-128 vs. AES-256 vs. CHCHA20-POLY1305.
