### ISSUE TITLE
Are SPDY etc. actually attacks?

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/server-side-tls#166]
On the wiki page these are listed under _12 Attacks on SSL and TLS_:

```
12.7 SPDY
12.8 TLS tickets (RFC 5077)
12.9 Cipher names correspondence table
12.10 GnuTLS ciphersuite
```

Could they be moved to 13?

**Comment by meineerde** [comment]
The SPDY and TLS tickets sections actually describe issues or potential attacks against the protocol or certain operational issues of using the respective feature. As such, leaving these sections inside of "Attacks on SSL and TLS" is correct.

The other two sections on cipher names suites though should probably be put into their own section, called e.g. "Cipher suites".
