### ISSUE TITLE
Extend scope to non-http servers?

### ISSUE THREAD

**Issue by allo-** [mozilla/server-side-tls#167]
What about extending the generator to support for example popular mail servers? And XMPP. And whatever else should use TLS by default.

Examples:
- postfix
- dovecot
- courier
- cyrus
- prosody
- ejabberd

**Comment by jvehent** [comment]
No something we directly need, but I'll be happy to review any patch for inclusion.

**Comment by allo-** [comment]
Where do i find the actual templates for the different servers?

And maybe someone should have a look at it, if the recommended ciphers are the same for web and others. I am no expert on choosing ciphers, so i am grateful for this project and just thought this could be merged with TLS-hardening howtos, which include more server softwares.

**Comment by tomato42** [comment]
XMPP should probably be as HTTP - you shouldn't even attempt unsecured connections with it

with SMTP it's a bit different, as basically all servers will retry with an unencrypted delivery if TLS fails, so allowing negotiation of weak ciphers is better than allowing it to fall back to plaintext

with POP3 and IMAP there are also common, new clients that _still_ default to TLSv1.0...

**Comment by allo-** [comment]
Where can i find the code/templates for the generated config files? I only see json files defining ciphersuites in this repo.

**Comment by april** [comment]
This is done in the newest version for at least some of these. It's very easy to add new templates, and I'd love contributions:

https://mozilla.github.io/ssl-config-generator/

**Comment by gene1wood** [comment]
Not all of the suggestions have been implemented in the new generator. If there are specific ones you want that aren't please open an issue on those [here](https://github.com/mozilla/ssl-config-generator/issues) or submit a PR
