### ISSUE TITLE
"Header always set" requires Apache >= 2.0.0

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/server-side-tls#171]
Apache 2.0 introduces support for conditionals, e.g. "Header always set"; prior to this, only "Header set" is available.

http://httpd.apache.org/docs/1.3/mod/mod_headers.html

http://httpd.apache.org/docs/2.0/mod/mod_headers.html

This affects the following code in the generator:

```
if (data.hstsEnabled == "true") {
    data.hsts = '\n    # HSTS (mod_headers is required) (15768000 seconds = 6 months)' + '\n' +
    '    Header always set Strict-Transport-Security "max-age=15768000"';
}
```

**Comment by april** [comment]
This is fixed in the newest version of the generator which takes this into account:
https://mozilla.github.io/ssl-config-generator/
