### ISSUE TITLE
Indicate supported clients

### ISSUE THREAD

**Issue by Yamakaky** [mozilla/server-side-tls#172]
For each profile, it would be good to add which version of the most popular clients are supported, like Firefox 40+, java 7+, IE 8+ on Vista and after... That would make it easier to make a choice. Maybe also relate with a database of browser market share to see an percentage approximation of the supported browsers.

**Comment by april** [comment]
Doesn't it already indicate that?

Configuration 	Oldest compatible client
* Modern: 	Firefox 27, Chrome 30, IE 11 on Windows 7, Edge, Opera 17, Safari 9, Android 5.0, Java 8
* Intermediate: 	Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android 2.3, Java 7
* Old: 	Windows XP IE6, Java 6 

Is there something that I'm missing?

**Comment by Yamakaky** [comment]
Wow, my bad...
