### ISSUE TITLE
OpenSSL 1.0.2j doesn't supports CHACHA (debian)

### ISSUE THREAD

**Issue by anantshri** [mozilla/server-side-tls#176]
chacha ciphers support started from 1.1.0 but when selecting 1.0.2j as version of openssl we still get recommended list with chacha in it.

I suppose 1.0.2j is from jessie backports in my distro and as it appears likely debian 9 will have support for these ciphers not anytime sooner. Can we correct this to point to proper config.

**Comment by april** [comment]
OpenSSL should ignore any cipher suites that it doesn't recognize.  Are you having problems with startup or something?  Including ChaCha20 allows it to work for sites with newer OpenSSL versions, and shouldn't have any downsides for sites that don't.

**Comment by anantshri** [comment]
I agree that openssl ignores what's not working but having that as a recommended options gives a false sense that chacha might be working on that openssl version. When version is clearly specified i would suggest we remove chacha from the list when it will not be realistically supported. Although ensuring 1.1.0+ version of openssl do give that out as recommendation.

Does that makes sense.

**Comment by tomato42** [comment]
the point is also that when the system is updated later, the configuration doesn't have to be updated, so if the new admin forgets to update the configuration (happens more often that we'd like to see), it will automatically pick up the new secure ciphers and not limit itself to old stuff

**Comment by anantshri** [comment]
valid point, but then don't you think this rationale needs to be said out loud somewhere. may be comment block stating chacha is not supported by current openssl but for future compatibility we are adding it here.

**Comment by zofrex** [comment]
I concur with anantshri, having been confused by this earlier today. I was expecting ChaCha20 to work and it took a bit of head-scratching to realise it was the OpenSSL version to blame.

The argument to include it for future selection definitely resonates with me, so I like the sound of a comment explaining the situation.

**Comment by lukastribus** [comment]
On the wiki, we already note:

> Older versions of OpenSSL may not return the full list of algorithms. AES-GCM and some ECDHE are fairly recent, and not present on most versions of OpenSSL shipped with Ubuntu or RHEL. This listing below was obtained from a freshly built OpenSSL. If your version of OpenSSL is old, unavailable ciphers will be discarded automatically. Always use the full ciphersuite and let OpenSSL pick the ones it supports.

Wiki is linked from the config generator.

**Comment by floatingatoll** [comment]
Can the generator page clearly state, right above the cipher string, something like:

"OpenSSL will ignore unsupported ciphers, so we provide a complete description of our preferred ciphers, and OpenSSL will simply ignore the ones it can't negotiate. If, someday, OpenSSL is updated to include support for those ciphers, simply restarting any SSL-enabled services will enable the newly-added ciphers ready and waiting in your cipherstring."

**Comment by gene1wood** [comment]
@floatingatoll Sounds like a good idea, want to PR it?

**Comment by floatingatoll** [comment]
I won't be able to this quarter, sorry.

**Comment by april** [comment]
The newest version of the guidelines do indeed state this.  :)
