### ISSUE TITLE
"Fork me on Github" banner partially obscures the content

### ISSUE THREAD

**Issue by AD7six** [mozilla/server-side-tls#18]
As can be seen in this screenshot:

![screenshot from 2014-11-27 15 32 57](https://cloud.githubusercontent.com/assets/33387/5218232/c00e07ba-764a-11e4-9925-e43f6537caef.png)

Depending on screen resolution the form is partially obscured, making the radios for switching server appear not to work.

**Comment by gene1wood** [comment]
@AD7six thanks for catching that. That's what I get for making changes without a QA cycle =)

**Comment by AD7six** [comment]
:)

Very nice work btw.
