### ISSUE TITLE
Feature request: only essentials

### ISSUE THREAD

**Issue by dm-coding** [mozilla/server-side-tls#181]
Hi there! Great project!

I think it would be really useful it was possible, as an option, to generate only the SSL configuration and not additionals like the vhost open and close tags, server name, etc. Combined with an option to download the result as text-only, it would be very useful to automatic inclusion in system configuration utilities. 

For example, I imagine a scenario where I could write an ansible task which would find the openssl and nginx version installed on the server, then grab the SSL configuration from this tool, and insert only the SSL directives into my own vhost template.

**Comment by jvehent** [comment]
I think you want the JSON version of the guidelines: https://statics.tls.security.mozilla.org/server-side-tls-conf.json
