### ISSUE TITLE
Annotate variables in configs

### ISSUE THREAD

**Issue by gene1wood** [mozilla/server-side-tls#187]
We should think about if there's a way to annotate the sections of the configurations that should be modified before use (e.g. `/path/to/signed_certificate` and `<IP DNS resolver>`) as it's not clear what's a variable and what's part of the config.

Alternatively we should change `<IP DNS resolver>` to be more obviously something to be replaced .

**Comment by april** [comment]
The newest version of the generator includes nice comments to help push people in the right direction.  :)
