### ISSUE TITLE
Encrypt to backend - HTTPS configs

### ISSUE THREAD

**Issue by blagoeres** [mozilla/server-side-tls#188]
What do you think about adding configuration for encryption to the backend when for example Nginx acts as a HTTPS client ?

**Comment by jvehent** [comment]
Could you explain a bit more what use case you're considering?
Are you using nginx as a reverse proxy in front of a local application, and enabling HTTPS between the reverse proxy and the application?

**Comment by lukastribus** [comment]
I think this is very hard to standardize, as backend TLS has a lot of different use-cases.

Do you use public CA's from a Mozilla, an OS provided CA list or maybe just a single public CA?
Maybe you need to use a private CA?
Revoke certs? If yes, via CRL or OCSP?

Those are not questions we can answer, but these are local policy questions that the administrator has to answer based on the requirements. We cannot dicate those.

Therefor, to avoid giving incomplete, out-of-context or wrong advice, I suggest we don't go there in the first place...

**Comment by blagoeres** [comment]
@jvehent Yes, that's what I thought. But it will probably make things complicated unnecessary.

**Comment by gene1wood** [comment]
@blagoeres If you've got a specific backend web server (for which nginx is acting as an HTTPS client) that you'd like to see, go ahead and either submit an issue calling out that backend webserver or even better, if you're familiar with it, submit a PR for that new web server.
