### ISSUE TITLE
Set ssl_ecdh_curve parameter in nginx config

### ISSUE THREAD

**Issue by zofrex** [mozilla/server-side-tls#189]
On the wiki page, for the modern suite it says:

> Certificate curve: prime256v1, secp384r1, secp521r1

But the generator doesn't include this in the nginx configuration.

I think this is right:

    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;

Compatibility info from [nginx's docs](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ecdh_curve):

> This directive appeared in versions 1.1.0 and 1.0.6.

> When using OpenSSL 1.0.2 or higher, it is possible to specify multiple curves (1.11.0)

So I think this means that for nginx >= 1.0.6:

    ssl_ecdh_curve prime256v1;

(that is, we want to pick just one, and I _think_ this is the best one but I am by no means certain about that)

And for nginx >= 1.11.0 _and_ openssl >= 1.0.2:

    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;

And for nginx < 1.0.6, leave it out altogether.

I'm willing to take a crack at the PR for this myself if y'all are happy with the plan.

(I'm assuming that highest priority goes first in the nginx config (not documented as far as I can see) and that we want larger numbers first, both assumptions need checking)

(edit: via the handshake simulation in SSLLabs, it does appear that highest priority goes first)

**Comment by tomato42** [comment]
looks good

**Comment by zofrex** [comment]
I'm not sure what the choice should be for older nginx/openssl when we have to pick just one.

"prime256v1" is the traditional conservative choice, but with "secp521r1:secp384r1:prime256v1" in place and using the modern ciphersuite I'm seeing zero handshakes from SSLLabs using prime256v1, everything is using 384 or 521, so it seems like 384 might be a better choice?

That's not the most rigorous of reasoning... but I'm struggling to find decent data on curve support in browsers. Thoughts?

**Comment by tomato42** [comment]
Common clients, yes, they basically all support at least P-256 and P-384. But at the same time, vast majority of servers supports _only_ P-256, so uncommon clients are likely to expect that P-256 is always supported by server. No, I do not have an example of such a client.

Secondly, there's little reason to default to the P-384, the server certificate won't have such a strong key anyway.

**Comment by andrewdunndev** [comment]
I was just looking into this and this was the response that I crafted:

Why not include `ssl_ecdh_curve` like what is mentioned in [cipherli.st](https://cipherli.st/). A combination of [these](https://github.com/openssl/openssl/issues/2188#issuecomment-271097503) [two](https://github.com/openssl/openssl/issues/2033#issuecomment-271163488) comments that ultimately say the specification in config of the `ssl_ecdh_curve` constrains the server's certificate, where `OpenSSL` must be able to choose the ECDHE curve based on the intersection of the server and client supported curves list.

**Comment by zofrex** [comment]
From the first of those links to openssl: "not setting the curves explicitly is likely better".

I didn't realise the constraint problems detailed there when I opened this issue. I'm loathe to push forward with this now unless someone is very sure it won't cause issues.

**Comment by floatingatoll** [comment]
Your original request is still worth considering - I think the discussion on 'which curves are better' can be rephrased as:

<b>Q:</b> When applying TLS Modern or Intermediate to a service, if we may either constrain to one curve, or permit all curves, which choice is appropriate?

Looking through the various requirements, it seems like writing them as a simple set of rules may help grasp the logic required:

Default values:

- Nginx 1.0.6+ implement `ssl_ecdh_curve`, default value `prime256v1`.
- Nginx 1.11.0+ changes the `ssl_ecdh_curve` default value to `auto` if OpenSSL 1.0.2+.

Override values:

- Nginx 1.0.6+ permits `ssl_ecdh_curve` to specify a single curve, overriding the default.
- Nginx 1.11.0+ changes `ssl_ecdh_curve` to permit multiple curves if OpenSSL 1.0.2+.

Looking at this, there's a simple reduction that could be implemented by someone easily in the generator code:

<b>A:</b> Output `ssl_ecdh_curve` only if Nginx 1.11.0+ and OpenSSL 1.0.2+, avoiding the problem entirely.

**Comment by floatingatoll** [comment]
TLS Modern, Intermediate, and Old all *currently* say:

> prime256v1, secp384r1, secp521r1

So that's likely the final value that needs to be output by the config generator (except with `:` instead of `, ` delimeters, per Nginx docs), but only in the 1.11.0+ & 1.0.2+ scenario.

(Discussion about whether these are 'good' or 'bad' curves is a topic for a different bug/issue, and by only emitting the config parameter when we can specify *all* curves, we don't need to select *one* curve as 'best' here, which drastically simplifies things.)

**Comment by april** [comment]
nginx actually chooses fairly sane defaults here, so I'm inclined to not include it in the generator unless that changes.  :)
