### ISSUE TITLE
Public Key Pinning (HPKP)

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/server-side-tls#19]
Please consider adding [Public Key Pinning](https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning).
Chrome already supports it.

**Comment by jvehent** [comment]
HPKP sounds great, but it's also a very young standard that needs to mature a bit. We're experimenting with it, and will update the Server Side TLS guidelines when we have a setup that makes sense. We don't want to rush a recommendation that could induce bad pining and break websites.

It will be some time before we add it to the standard configuration, so closing this for now.
