### ISSUE TITLE
JSON versions of TLS recommendations: hsts_min_age -> hsts_max_age ?

### ISSUE THREAD

**Issue by gingerbus** [mozilla/server-side-tls#192]
Just checking to see if the 'hsts_min_age' parameter is mis-named in the JSON versions of the recommendation? It looks like it should be *max* rather than *min*, as its a max value that gets set in the header?

https://github.com/mozilla/server-side-tls/blob/gh-pages/json/server-side-tls-conf-4.0.json

**Comment by jvehent** [comment]
We recommend a minimum age to provide the adequate amount of security.
The browsers need a maximum age to expire the value internally.
It's named correctly.
