### ISSUE TITLE
Libressl support

### ISSUE THREAD

**Issue by Adriel-M** [mozilla/server-side-tls#193]
How about including libressl support? I doubt there will be a lot of difference between an openssl config and a libressl config.

**Comment by floatingatoll** [comment]
Adriel, since you're working with LibreSSL, can you run our config
generator for various OpenSSL versions and see if it works just fine or
breaks somehow?

**Comment by gene1wood** [comment]
Ya, @Adriel-M if you could test and confirm/disconfirm that the configs generated already work with libressl that would be helpful. If they don't and you can call out what would need to change or submit a PR we could move on this.

**Comment by april** [comment]
Closing due to age, I think most things should be compatible in general.

**Comment by Popolon** [comment]
Most thing of which version of OpenSSL should be compatible with which version of LibreSSL ?

**Comment by floatingatoll** [comment]
LibreSSL doesn’t appear to support TLS 1.3, so it won’t be able to enable
Modern 5.0 at all. From their site, also:

> LibreSSL is API compatible with OpenSSL 1.0.1, but does not yet include
all new APIs from OpenSSL 1.0.2 and later. LibreSSL also includes APIs not
yet present in OpenSSL. The current common API subset is OpenSSL 1.0.1.

So in lieu of generator support for it directly, you might be able to use
the 1.0.1 options for some compatibility on Intermediate 5.0 or Okd 5.0 —
but be careful to validate that all Intermediate ciphers are enabled, or
else it may break all clients.
