### ISSUE TITLE
TLS selectable

### ISSUE THREAD

**Issue by gronau-it-cloud-computing** [mozilla/server-side-tls#194]
please expand the selection for generation for TLS for defining like checkboxes if TLS 1.0, TLS 1.1, TLS 1.2 and TLS 1.3. Default only TLS 1.2 and TLS 1.3 should be preselected

**Comment by floatingatoll** [comment]
Mozilla's recommended TLS and cipher guidelines are grouped into Modern,
Intermediate, Old. We evaluate these choices carefully and update them from
time to time.

This generator implements only those guidelines, and does not serve as a
customizable "pick and choose" security worksheet. Instead, it adapts the
guidelines  of your choice to your chosen software version's ability to
support it.

Expanding the generator to permit customizations would conflict directly
with the goal of providing stock baseline secure configurations, and is
unlikely to occur. You're welcome of course to fork it and implement this
yourself, though!
