### ISSUE TITLE
NSS is missing in the config generator

### ISSUE THREAD

**Issue by darix** [mozilla/server-side-tls#196]
e.g. apache has a mod_nss

**Comment by gene1wood** [comment]
@darix Can you give me an example config line that should be added or removed from the generated apache config so I better understand?

**Comment by tomato42** [comment]
Example config:
```
NSSEngine on
NSSCipherSuite +rsa_rc4_128_md5,+rsa_rc4_128_sha,+rsa_3des_sha,-rsa_des_sha,-rsa_rc4_40_md5,-rsa_rc2_40_md5,-rsa_null_md5,-rsa_null_sha,+fips_3des_sha,-fips_des_sha,-fortezza,-fortezza_rc4_128_sha,-fortezza_null,-rsa_des_56_sha,-rsa_rc4_56_sha,+rsa_aes_128_sha,+rsa_aes_256_sha
NSSProtocol SSLv3,TLSv1,TLSv1.1,TLSv1.2
NSSNickname Server-Cert
NSSCertificateDatabase /etc/httpd/alias
NSSVerifyClient none
<Directory "/var/www/cgi-bin">
        NSSOptions +StdEnvVars
</Directory>
```

**Comment by lhirlimann** [comment]
https://pagure.io/mod_nss

**Comment by woodda** [comment]
Landing on this topic in June 2018,, nearly a year later.  It sure would be handy to have that mod_nss vs. mod_ssl sub-option available under Apache on the generator page, given that so many of us are using mod_nss out here.

**Comment by april** [comment]
This would be a pretty huge piece of work, but if you're interested in submitting a PR I would be happy to take a look here:

https://github.com/mozilla/ssl-config-generator

Thanks!
