### ISSUE TITLE
unexpected "E" with current openssl & nginx and modern setting

### ISSUE THREAD

**Issue by cptn-cosmo** [mozilla/server-side-tls#199]
nginx version: nginx/1.13.4
OpenSSL 1.1.0f  25 May 2017

nginx -t
2017/09/22 16:06:16 [emerg] 469#469: unexpected "E" in /etc/nginx/conf.d/domain.com.conf:49
nginx: configuration file /etc/nginx/nginx.conf test failed

Line 49:

    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';

**Comment by floatingatoll** [comment]
Nginx may not permit quoting of the ssl_ciphers string in that way. Did our
generator output those single-quotes? Please try removing them and see if
the problem goes away.

https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers

**Comment by cptn-cosmo** [comment]
Yes, the generator did output the line this way:

`    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
`

**Comment by floatingatoll** [comment]
Does removing the single quotes fix it on your nginx 1.13.4?

**Comment by jrchamp** [comment]
Alternatively, try double quotes instead of single quotes?

**Comment by cptn-cosmo** [comment]
> Does removing the single quotes fix it on your nginx 1.13.4?

Yes, removing the quotes resolves the issue.

**Comment by Mattia98** [comment]
Why is this issue still open? Is it fixed or not?

**Comment by lukastribus** [comment]
It's not fixed.

**Comment by april** [comment]
This is fixed in the new version:

https://mozilla.github.io/ssl-config-generator/
