### ISSUE TITLE
Node.js sample configurations?

### ISSUE THREAD

**Issue by dahjelle** [mozilla/server-side-tls#20]
I realize configuring a Node.js server is a bit of a different beast than the other servers…but it'd be nice to have some examples of how to configure the built-in HTTPS server in Node.js to your recommendations.

Thanks for the great resource!

**Comment by gene1wood** [comment]
Great idea. Can you provide some example configs to work from?

**Comment by dahjelle** [comment]
Well, I'm not any sort of HTTPS or HTTPS-in-Node expert, but I can definitely throw in some example configs (from my own code and the docs) that perhaps can serve as the basis for experts to modify?

``` javascript
var https = require('https');
var fs = require('fs');

var options = {
    key: fs.readFileSync('key.pem'),
    cert: fs.readFileSync('cert.pem'),
    ciphers: [
        'ECDHE-RSA-AES256-SHA384',
        'DHE-RSA-AES256-SHA384',
        'ECDHE-RSA-AES256-SHA256',
        'DHE-RSA-AES256-SHA256',
        'ECDHE-RSA-AES128-SHA256',
        'DHE-RSA-AES128-SHA256',
        'HIGH',
        '!aNULL',
        '!eNULL',
        '!EXPORT',
        '!DES',
        '!RC4',
        '!MD5',
        '!PSK',
        '!SRP',
        '!CAMELLIA'
    ].join(':'),
    ecdhCurve: 'prime256v1', // this is the default
    honorCipherOrder: true,
    secureOptions: require('constants').SSL_OP_NO_SSLv3|require('constants').SSL_OP_NO_TLSv1|require('constants').SSL_OP_NO_SSLv2
};

https.createServer(options, function (req, res) {
  res.writeHead(200);
  res.end("hello world\n");
}).listen(8000, '127.0.0.1');
```

Most of that configuration is from the [Node.js TLS documentation](http://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener), with bits from the [HTTPS documentation](http://nodejs.org/api/https.html) and the list of ciphers from [io.js](https://iojs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener)'s default list (more discussion on that list is on the [pull request](https://github.com/iojs/io.js/pull/826)).

Again, I'm not qualified to certify or recommend this configuration, but hopefully it can serve as a starting point!

**Comment by mikemaccana** [comment]
It might be better to simply port the whole thing to node. ie, rather than generate a config, and loading that with node, have a module that sets options accordingly - that way, when the module is updated, the cyphers are updated.

**Comment by dahjelle** [comment]
I definitely like the idea of an NPM module, or perhaps a collection of them for each of the compatibility options. Perhaps something that would simplify the code above to something like:

``` javascript
var https = require('https');
var fs = require('fs');
var mozTLS = require('moz-tls');

var options = mozTLS.modern({
    key: fs.readFileSync('key.pem'),
    cert: fs.readFileSync('cert.pem')
});

https.createServer(options, function (req, res) {
  res.writeHead(200);
  res.end("hello world\n");
}).listen(8000, '127.0.0.1');
```

or some such. Perhaps it could even validate the keys themselves to conform to recommendations?

**Comment by mikemaccana** [comment]
@dahjelle exactly. I'm going to have a go at this tomorrow, will let you know once 0.0.1 is published.

**Comment by dahjelle** [comment]
@mikemaccana Sweet! Thanks! I'm looking forward to it!

**Comment by mikemaccana** [comment]
Just published: https://www.npmjs.com/package/ssl-config

which in turn relies on another new package https://www.npmjs.com/package/minimum-tls-version

**Comment by dahjelle** [comment]
@mikemaccana Awesome! Thanks for doing this—I've put it on my list to implement in our app. Much appreciated!

**Comment by gene1wood** [comment]
So it looks likes this is completed now that @mikemaccana published his npm.

If there's any way you can think of for future Mozilla ciphersuite changes to be rendered into your nodejs module, let me know. Nothing clever is coming to mind.

**Comment by mikemaccana** [comment]
@gene1wood I'm now watching the `server-side-tls` project, so should see all updates.
