### ISSUE TITLE
Add support for MySQL

### ISSUE THREAD

**Issue by sdann** [mozilla/server-side-tls#200]
In some of my recent security research, I've found that the default TLS configurations on even the latest MySQL instances are insecure. Providing, per-version guidance on the proper TLS configuration parameters for MySQL would be just as useful as it is for Apache and Nginx.

Problems with the current defaults are enumerated in a presentation I gave at:
http://www.danneman.org/presentations/Automating_TLS_Configuration_Verification.pdf

I've listed what I believe are the most secure settings possible in version 5.7.19 on a recent blog post at:
https://blog.securityinnovation.com/automating-tls-configuration-verification

I've also copied them below:

MySQL Community Edition (built with yaSSL):
tls_version = TLSv1.1
ssl-cert    = {certificate file name}
ssl-key     = {secret key file name}
ssl-cipher  = DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA
require_secure_transport = ON 

MySQL Enterprise Edition (built with OpenSSL): 
tls_version = TLSv1.2
ssl-cert    = {certificate .pem file name}
ssl-key     = {secret key.pem file name}
require_secure_transport = ON 

Note, that the tool will have to distinguish between the 2 different editions of MySQL, each of which use a different TLS library.

Also, as the Community Edition doesn't support TLS 1.2, the tool should probably not even display a "Modern" configuration but rather only an "Intermediate"

I don't have a lot of context on proper installs for versions older than current, but I do have the following MySQL parameter history charted out.

Version | Release Date | New Features | Notes
-- | -- | -- | --
5.7.19 | 2017-07-17 |    | Current
5.7.10 | 2015-12-07 |  TLSv1.1 and TLSv1.2 supported. |  
5.7.8 | 2015-08-03 |  require_secure_transport server option | Server will disallow non-encrypted connections.
5.5.0 | 2009-12-07 |  TLSv1.0 available | Available before this, but this is the oldest, currently supported, version.

**Comment by april** [comment]
This is completed in the newest version:

https://mozilla.github.io/ssl-config-generator/

**Comment by gene1wood** [comment]
It [looks like](https://github.com/mozilla/ssl-config-generator/blob/master/src/templates/partials/mysql.hbs) the implementation is only for one "mysql" instead of the two editions which may not capture these differences in pem filename or tls version.

**Comment by april** [comment]
You want to open up an issue on the other repo for me, please? Thanks!
