### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by sdann** [mozilla/server-side-tls#201]
In some of my recent security research, I've found that the default TLS configurations on even the latest PostgreSQL instances are insecure. Providing, per-version guidance on the proper TLS configuration parameters for PostgreSQL would be just as useful as it is for Apache and Nginx.

Problems with the current defaults are enumerated in a presentation I gave at:
http://www.danneman.org/presentations/Automating_TLS_Configuration_Verification.pdf

I've listed what I believe are the most secure settings possible in version 9.5.7 on a recent blog post at:
https://blog.securityinnovation.com/automating-tls-configuration-verification

I've also copied them below:

postgresql.conf:
ssl = on
ssl_ciphers    = 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256'
ssl_prefer_server_ciphers = on
ssl_ecdh_curve = 'prime256v1'
ssl_cert_file  = <full path to certificate .pem file>
ssl_key_file   = <full path to sercret key .pem file>

pg_hba.conf:
hostssl all             all             <CIDR address of client range>         md5

PostgreSQL splits TLS settings into the normal .conf file, and TLS enforcement into a separate network ACL file pg_hab.conf. The configuration generator tool can probably leave this second file out.

Below is the limited TLS implementation history in PostgreSQL that I've tracked so far.

Version | Release Date | New Features | Notes
-- | -- | -- | --
9.6.3 | 2017-05-11 |   | Current
9.6.0 | 2016-09-29 | Support OpenSSL 1.1.0 |  
9.5.7 | 2017-05-11 |   | Ubuntu 16.04.2

**Comment by april** [comment]
This is completed in the newest version:

https://mozilla.github.io/ssl-config-generator/
