### ISSUE TITLE
Use shorter alternatives for HAProxy modern SSL protocol config

### ISSUE THREAD

**Issue by josephapg** [mozilla/server-side-tls#209]
`force-tlsv12` and `ssl-min-ver TLSv1.2` (for TLSv1.3 support) are shorter than `'no-sslv3 no-tlsv10 no-tlsv11'`.

**Comment by floatingatoll** [comment]
For potential implementors, force-tlsv12 was added in 1.5-dev13 (2012-11),
ssl-min-ver was added in 1.8-dev2 (2017-06).

**Comment by jrchamp** [comment]
Are those configuration options equivalent? Specifically, does it put the connection in the same state?

**Comment by josephapg** [comment]
@jrchamp 

`ssl-min-ver TLSv1.2` is equivalent to the current config, but as @floatingatoll said, only HAProxy 1.8-dev2 and up support this.

`force-tlsv12` enables TLSv1.2 and disables other versions of the protocol, but it has been supported since 1.5-dev13. It's the same as nginx's modern config in the generator.

**Comment by floatingatoll** [comment]
Does “force-tlsv12” disable TLSv1.3 support?

(If 1.3 isn’t implemented yet, does “force-tlsv1.1” disable TLSv1.2
support?)

**Comment by josephapg** [comment]
@floatingatoll 

> If 1.3 isn’t implemented yet, does “force-tlsv1.1” disable TLSv1.2 support?

Yes, it disables TLSv1.2.

Edit: forgot the ">"

**Comment by lukastribus** [comment]
Note that `ssl-min-ver` and `ssl-max-ver` require either boringssl or OpenSSL 1.1.1.

**Comment by floatingatoll** [comment]
I don’t think it makes sense to apply this change. Forcing 1.2 rather than excluding v3 and 1.0 and 1.1 has troubling concerns for 1.3 support.

**Comment by rhclayto** [comment]
> 
> 
> I don’t think it makes sense to apply this change. Forcing 1.2 rather than excluding v3 and 1.0 and 1.1 has troubling concerns for 1.3 support.

I don't think `ssl-min-ver TLSv1.2` disables v1.3 or above.

**Comment by april** [comment]
Given the choice of having something that is compatible with all versions of HAProxy or having ifdefs to generate a very slightly shorter config file, I think it's probably best to just do the prior.

We can certainly revisit this in a couple of years, where we can just set `ssl-min-ver` instead.
