### ISSUE TITLE
Drop Deprecated 3DES Cipher

### ISSUE THREAD

**Issue by jrchamp** [mozilla/server-side-tls#211]
We're coming up on the anniversary of NIST's message to drop 3DES: https://csrc.nist.gov/news/2017/update-to-current-use-and-deprecation-of-tdea

This will also resolve #210

**Comment by jvehent** [comment]
My last measurements [from 18 months ago showed 3DES at 2.8% of traffic](https://j.vehent.org/blog/index.php?post/2016/08/04/TLS-stats-from-1.6-billion-connections-to-mozilla.org), which is still too high to drop it from the intermediate level. This may have changed recently, but we need data to justify dropping it.

**Comment by klaver** [comment]
Why trying to keep things alive that shouldn't be?

The only major browsers and Operating System utilizing 3DES is Internet Explorer versions 6 to 8 running at WindowsXP. These browsers are deprecated and unsupported by Microsoft since January 12, 2016. WindowsXP is out-of-service since april 8, 2014.

OpenSSL does not include 3DES per default since version 1.1.0 (August 2016), and considers it a "weak cipher".

**Comment by tomato42** [comment]
there is also embedded edition of XP, and you can buy extended support for regular too

https://support.microsoft.com/en-ie/help/18581/lifecycle-faq-windows-products

they are supported till April 9, 2019

**Comment by klaver** [comment]
Even with extended support for the underlying OS, using IE 6-8 browsers is still a major security risk. Chrome or Firefox are better alternatives and both use stronger ciphers.

**Comment by ekr** [comment]
The primary risk of 3DES is to confidentiality with very large data volumes. That's not ideal, but I don't think it's critical to remove either.

**Comment by Mattia98** [comment]
I agree that 3DES should be dropped. It's essentially dead. Those who still need it will act accordingly and not copy paste configs they find online.

**Comment by ekr** [comment]
@jvehent: has anything changed since May? If not, I suggest we close this.

**Comment by jvehent** [comment]
I need to rerun the data to see if 3DES usage has changed at all.

**Comment by klaver** [comment]
@jvehent when you re-run the statistics, please try to intersect with browser and OS version information if possible

**Comment by april** [comment]
This has been dropped from 5.0 in everything except the Old configuration.
