### ISSUE TITLE
Warn on HSTS and ELB

### ISSUE THREAD

**Issue by cmgbhm** [mozilla/server-side-tls#223]
As far as I'm aware, there is no ability of AWS ELBs to set a Strict-Transport-Security header on behalf of the proxied URL.   Loading the server-side-tls tool with the field set and not set returns the same configuration as well. 

It would be good just to warn people that they need to solve that at the proxied application layer's server configuration rather than thinking ELB would will solve that for them.

**Comment by opsarno** [comment]
Do you use the seven level forwarding mode?
Maybe you can use four level of forwarding to control the header.

**Comment by april** [comment]
The new version of the config generator grays out the option when you select ELBs:

https://mozilla.github.io/ssl-config-generator/
