### ISSUE TITLE
HSTS: includeSubDomains is not included in the header

### ISSUE THREAD

**Issue by JensTimmerman** [mozilla/server-side-tls#224]
```
    # HSTS (mod_headers is required) (15768000 seconds = 6 months)
    Header always set Strict-Transport-Security "max-age=15768000"
```

This should also have: includeSubDomains

**Comment by floatingatoll** [comment]
Adding includeSubDomains by default would harm the unwary unnecessarily. We
must not include that in any default recommendation or example. Some
domains have hosts underneath them that must not upgrade requests yet.
While sub-optimal in the long-term, it’s essential to take that into
account here.

**Comment by JensTimmerman** [comment]
Can the comment above this header make note of the includeSubDomains option? Let people know it exists and warn them about it's implications?

**Comment by jvehent** [comment]
That's reasonable. Can you submit a patch?

**Comment by april** [comment]
While I think it's reasonable, I'm not sure I want to add it. It'll take just one person clicking the button to start receiving endless screaming. 😰
