### ISSUE TITLE
Feature Request: replace the Google CDN with other provider

### ISSUE THREAD

**Issue by popcorner** [mozilla/server-side-tls#232]
This webpage is now using Google CDN (ajax.googleapis.com), but maybe it should be replaced, which may make this website more accessible.
### Reason:

- If these javascript are not loaded, the website won't work.
- There are many nice public CDNs, like cdnjs and jsdelivr, which have better performance.
- CDNs like jsdelivr integrate many different providers, and have more uptime for users.
- All these CDNs are available worldwide, but Google CDN doesn't. For example, the CDNs above are all available in mainland China and jsdelivr even have servers in China. But ajax.googleapis is not a legal website in China and not accessible, which makes 20% of people in the world unavailable to use this website.

**Comment by gene1wood** [comment]
@popcorner Sounds good, want to PR the change?

**Comment by floatingatoll** [comment]
Mozilla has existing CDN agreements that presumably include data safety guarantees to protect our visitors' privacy. Please consider selecting a CDN here that is covered by one of those agreements.

**Comment by popcorner** [comment]
@floatingatoll Is there any links about that agreement? I searched on the Internet but didn't find that.
I read the privacy policy of the jsdelivr CDN and it claims that it doesn't track users or collect any user data.
I can't find the privacy policy of cdnjs, but it is an open source project, which may seem reliable.
Both of them seems to be better than Google which this website now using when talking about privacy.

**Comment by floatingatoll** [comment]
Those agreements would not generally be public, which I understand may make
it difficult for you to respond to that comment; it's primarily meant for
our own staff to keep in mind as they evaluate your changes.

**Comment by popcorner** [comment]
@floatingatoll Sorry, I didn't realize that. But you may consider this suggestion, Google CDN doesn't seems to be a good choice, especially for people in some certain areas.
@gene1wood I created a demo here: https://popcorner.github.io/server-side-tls/ssl-config-generator/
In this demo, I changed the CDN to jsdelivr because of its performance. One of the files is not found in NPM(jsdelivr relies on NPM) so I use cdnjs instead.
I'm not sure if these choices are suitable for your policies so I didn't make a PR now. You can evaluate it and tell me if that is acceptable.

**Comment by popcorner** [comment]
p.s, when I test the website, I see a file https://mozorg.cdn.mozilla.net/en-US/tabzilla/tabzilla.js response with 403 Forbidden. I'm not sure if this is caused by my network or the server itself.

**Comment by floatingatoll** [comment]
Tabzilla is decommissioned. You should open a new issue about that, separate from this one, since we'll need to repair that regardless of the CDN issue.

**Comment by gene1wood** [comment]
How does this look ( #234 )? This switches to CloudFlare which appears to have a robust privacy policy.

**Comment by popcorner** [comment]
@floatingatoll Thank you. I didn't open a new issue because I'm not sure if it is an issue. Now I create it here #233 .

**Comment by april** [comment]
This was fixed in the new version of the config generator, which uses webpack and keeps everything local:

https://mozilla.github.io/ssl-config-generator/
