### ISSUE TITLE
Tabzilla in ssl config generator is not working

### ISSUE THREAD

**Issue by popcorner** [mozilla/server-side-tls#233]
When visiting https://mozilla.github.io/server-side-tls/ssl-config-generator/ ,the file [tabzilla.js](https://mozorg.cdn.mozilla.net/en-US/tabzilla/tabzilla.js) can't be loaded and return 403 Forbidden.

**Comment by floatingatoll** [comment]
Tabzilla is deprecated and will not be available going forward. Please
switch to a more current Mozilla site theme; the Bedrock team can be of
assistance if needed.

**Comment by gene1wood** [comment]
Ya, #235 i my interim step that's faster and easier than redesigning the UI. Hoping to prevent the perfect from becoming the enemy of the good.

**Comment by floatingatoll** [comment]
Certainly no objections here!

**Comment by april** [comment]
This was all fixed and cleaned up in the new version, thanks!

https://mozilla.github.io/ssl-config-generator/
