### ISSUE TITLE
The new ssl config generator's url

### ISSUE THREAD

**Issue by popcorner** [mozilla/server-side-tls#253]
I see there is a new repo for the ssl config generator. Is there any future plan to update the generator in this repo?
If the generator here is deprecated, adding a redirection or adding a link to the new URL may be useful. Many websites(like https://wiki.mozilla.org/Security/Server_Side_TLS) and search engine results are using the old URL (https://mozilla.github.io/server-side-tls/ssl-config-generator/) , users can't find the new one.

**Comment by gene1wood** [comment]
Yes, we'll be taking the existing generator and replacing with a js redirect so that all existing anchor tag links work and redirect to the new generator.
