### ISSUE TITLE
Forgets webserver version when switching from Intermediate to another profile

### ISSUE THREAD

**Issue by maurom** [mozilla/server-side-tls#256]
While trying to generate a new configuration for an old Apache server, I entered the following parameters:

Server: Apache
Profile: Modern
Server Version: 2.4.10
OpenSSL Version: 1.0.1t
HSTS Enabled: True

Then, trying to spot differences in the recommended statements, I clicked on Old profile and saw that "SSLSessionTickets off" was added to the configuration. This settings is not available on 2.4.10, so it sounded strange.

It turns out the value in Server Version is automatically replaced by 2.4.34 any time there is a change in the configuration profile. Is this an expected behavior of the generator?

Thanks in advance,

**Comment by april** [comment]
Which website are you using? The old website will be going away soon, to be replaced by:

https://ssl-config.mozilla.org/

Is it happening there?

**Comment by maurom** [comment]
Oh, I was using the old website (mozilla.github.io) courtesy of google search.
The new website works ok (at least when regarding to this ticket).
Sorry and thanks for your quick reply.

**Comment by april** [comment]
No problem! The new website should be live in the next week or so.  :)
