### ISSUE TITLE
Update repository description

### ISSUE THREAD

**Issue by bmw** [mozilla/server-side-tls#257]
As of writing this it looks like:

![Screen Shot 2019-06-28 at 10 20 55 AM](https://user-images.githubusercontent.com/6504915/60359678-95414800-998e-11e9-87b5-f48cacf17334.png)

It's still linking to https://mozilla.github.io/server-side-tls/ssl-config-generator/ and should probably be updated to https://ssl-config.mozilla.org/.

**Comment by szepeviktor** [comment]
Oh! It took me 30 minutes to find.

Please @april

**Comment by april** [comment]
Done. Thanks for letting me know!
