### ISSUE TITLE
No modern configuration available with openSSL<1.0.1

### ISSUE THREAD

**Issue by dvigneron** [mozilla/server-side-tls#26]
Hi,
openSSL 0.9.8 and 1.0.0 don't support TLSv1.1 or TLSv1.2 (only appear with 1.0.1 cf http://en.wikipedia.org/wiki/OpenSSL#Major_version_releases), so the "Modern" configuration gave by the generator can't be used.
it may be a boog idea to replace the configuration by a warning/error message like "openSSL version does not support the requirement for a modern configuration"

**Comment by gene1wood** [comment]
Good catch. I'm working on the code for this. At the moment I'm stuck because openssl doesn't actually use real [semver](http://semver.org/) values. As a result the [method I'm using to compare versions](https://gist.github.com/cowboy/566233) incorrectly thinks that `1.0.1 > 1.0.1e > 1.0.1a` (instead of `1.0.1e > 1.0.1a > 1.0.1`). I'll find a way to do openssl version comparisons and add this in.

**Comment by ryanschwartz** [comment]
Came here to say this - your generator should not include "-TLSv1" if openssl < 1.0.1 is provided. Apache 2.2 reference: http://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslprotocol

**Comment by miken32** [comment]
Actually, I'm running Apache 2.2.15 and OpenSSL 1.0.1e on Scientific Linux 6.5 and I don't have TLS > 1.0. Both are standard packages installed with yum.

**Comment by thajek** [comment]
I'm running CentOS 6.6 and RHEL 6.6 both with Apache HTTPD 2.2.15 and OpenSSL 1.0.1e and I have TLSv1.0, TLSv1.1 and TLSv1.2?  Scientific is a RHEL derivative right?  You might check your version of mod_ssl, I believe TLSv1.x was added in 2.2.15-31 of mod_ssl.
Changelog for mod_ssl on Centos/RHEL 6.6:
    Tue Jun 10 2014 Jan Kaluza jkaluza@redhat.com - 2.2.15-31
    ...
    - mod_ssl: enable support at run-time for TLSv1.x with newer OpenSSL (#1034984)

Might be you just need to update mod_ssl.

**Comment by miken32** [comment]
That is the case. I was running security updates only and was on mod_ssl 1:2.2.15-31.sl6 according to yum. I did an update on our internal server and can confirm we now have TLS 1.2 on mod_ssl 1:2.2.15-39.sl6. Thanks for the tip!
This, of course, doesn't change the fact that OpenSSL 1.0.1 is no guarantee of having TLS 1.1+

**Comment by gene1wood** [comment]
I've updated the config generator to account for OpenSSL support of TLS v1.1 and v1.2. This doesn't address the possibility of having an up to date OpenSSL and Apache httpd, but an old mod_ssl.

Is it worth trying to address this case? I think it would require adding another version input box for the version of mod_ssl. If this is a rare case, it would be nice to avoid adding another input field.
