### ISSUE TITLE
Why 'ssl_prefer_server_ciphers off'?

### ISSUE THREAD

**Issue by feross** [mozilla/server-side-tls#260]
Hi there! Great work on this project ❤️

I'm curious why the nginx intermediate and modern configuration is recommending `'ssl_prefer_server_ciphers off'`? Thanks!

**Comment by april** [comment]
The guidelines talk about why we do this:

https://wiki.mozilla.org/Security/Server_Side_TLS

Namely, all the ciphers in Modern and Intermediate are secure. As such, we let the client choose the most performant cipher suite for their hardware configuration.

For the Old configuration, we still set `ssl_prefer_server_ciphers` to `on`.

**Comment by feross** [comment]
Great, thanks!

**Comment by OrangeDog** [comment]
Is there not something to be said, because many different clients connect to one server, that you should prefer the server's most performant option?

**Comment by april** [comment]
Server performance isn't really an issue in 2020. Most of them have tons of chips with AES acceleration. If you're running on a really slow server, you can make that change.

**Comment by OrangeDog** [comment]
That's my point. The server can likely do AES much faster than CHACHA, while many clients will be the opposite.

**Comment by april** [comment]
Okay? I guess I don't understand what you're trying to say then.

The server can do AES faster than CHACHA, but it's so fast either way that it's irrelevant. That's not the case for clients.

**Comment by jrchamp** [comment]
> you should prefer the server's most performant option?

You want to prefer to the client's most performant option. It will be a better experience for your users and it won't hurt their mobile device's battery life as much. The server is not the bottleneck.
