### ISSUE TITLE
Certificate properties in JSON file

### ISSUE THREAD

**Issue by fabian-hk** [mozilla/server-side-tls#267]
https://github.com/mozilla/server-side-tls/blob/39b9d77a55d6be25b78bba3798e4a8ffdf7c82af/json/server-side-tls-conf-5.0.json#L44

In the intermediate profile, ECDSA certificates are allowed but there are no certificate curves specified. Shouldn't this variable have the value ``["prime256v1", "secp384r1"]`` like in the modern profile?

https://github.com/mozilla/server-side-tls/blob/39b9d77a55d6be25b78bba3798e4a8ffdf7c82af/json/server-side-tls-conf-5.0.json#L16

Why is there a key size specified for RSA certificates in the modern profile? RSA certificates are not allowed in the modern profile.

The newest [5.3.json](https://ssl-config.mozilla.org/guidelines/5.3.json) file has the same values.

**Comment by april** [comment]
This was fixed here:

https://github.com/mozilla/ssl-config-generator/commit/c48ecf5dcf43d3ed0f1f0e6a85ca1ae336984f4c

https://ssl-config.mozilla.org/guidelines/5.4.json

Thanks for letting me know!
