### ISSUE TITLE
Adding recommended certificate type and certificate lifespan to the JSON file

### ISSUE THREAD

**Issue by fabian-hk** [mozilla/server-side-tls#269]
What about adding the recommended certificate type and certificate lifespan to the JSON file so that automatic test software can give warnings if another certificate type or a longer certificate lifespan is used by a server?

**Comment by april** [comment]
These should both be in there, as `certificate_types` and `maximum_certificate_lifespan`. Is there something that I'm missing?

Thanks!

**Comment by fabian-hk** [comment]
I know that the maximum certificate lifespan is in the JSON file but on the [website](https://wiki.mozilla.org/Security/Server_Side_TLS) with the profile descriptions there is also a recommended lifespan of 90 days in the intermediate and old profile.

The same goes for the certificate types in the intermediate profile. There are ECDSA and RSA certificates allowed but ECDSA is recommended.

So I was wondering whether you could add this information about the recommended values to the JSON file?

**Comment by april** [comment]
This is now done in version 5.5, which has `recommended_certificate_lifespan` and `maximum_certificate_lifespan` in its configuration.  :)
