### ISSUE TITLE
Certificate type: P-256 or P-384?

### ISSUE THREAD

**Issue by gwendal-g** [mozilla/server-side-tls#278]
Hello,

On [this page](https://wiki.mozilla.org/Security/Server_Side_TLS), it's indicated to use ECDSA certificates using P-256, as P-384 provides negligible improvements to security and Ed25519 is not yet widely supported.

Is it still up to date?

The upcoming ECDSA Let’s Encrypt root certificate will use P-384.
https://letsencrypt.org/certificates/#root-certificates

That's why I'm asking.

Thanks

**Comment by tomato42** [comment]
yes, it's still correct

the difference is between CA certificate and End Entity (server) certificate: CAs perform relatively few signatures so it's ok for them to spend few more cycles to create those signatures; servers create a lot of signatures, so you want to be fast here

so you use P-256 in the server certificate that gets signed by a P-384 certificate

(in general the the certificate path doesn't have to be uniform at all, you can have P-256 certificate signed with RSA, then that RSA certificate have signed with DSA)

**Comment by gwendal-g** [comment]
Ohh I didn't know. Thanks for the info. I did well to ask I think :)
