### ISSUE TITLE
Publishing?

### ISSUE THREAD

**Issue by pierreozoux** [mozilla/server-side-tls#28]
Hey!

You made great work by giving us access to this!
I wanted to add OCSP, but I saw it is already there!

Do you know when will it be available online here: https://mozilla.github.io/server-side-tls/ssl-config-generator/

Thanks a lot for your work!

**Comment by gene1wood** [comment]
@pierreozoux I'm not sure I understand. OCSP stapling is present in the code and is available at the URL you link to. Can you ask your question in a different way?

**Comment by pierreozoux** [comment]
Yes, sorry, I mistaken.
