### ISSUE TITLE
Hard to read cipherlist

### ISSUE THREAD

**Issue by itsbo** [mozilla/server-side-tls#29]
The cipherlists are very hard to read and understand. I have no long discussion thread to back this up, but if there is something to contradict me, please point me that way. It's just from my experience that easier to understand configs are more readily adopted.

I'd also differentiate between 2.2 and 2.4 version of Apache. For 2.4 I'd drop RSA except RSA+3DES for IE8 (XP), as everything else talks (EC)DHE AFAIK.

These practically do the same as the long ones but are easier to understand:

Apache 2.2 intermediate: ALL:+RSA:+RSA+3DES:!MEDIUM:!LOW:!EXPORT:!NULL:!aNULL
Apache 2.2 modern: ALL:+RSA:!MEDIUM:!LOW:!EXPORT:!NULL:!aNULL:!3DES:!CAMELLIA

Apache 2.4 intermediate: ALL:-RSA:RSA+3DES:!MEDIUM:!LOW:!EXPORT:!NULL:!aNULL
Apache 2.4 modern: ALL:!RSA:!MEDIUM:!LOW:!EXPORT:!NULL:!aNULL:!3DES:!CAMELLIA

Apache filters these away automatically: "!SRP:!DSS:!PSK:!kECDH".

While I agree that you can do a lot of fine tuning with explicitely stating all ciphers as you have done, if TLS1.2 connections do not accept cipher outside the TLS 1.2 spec, the intermingled ciphers from below 1.2 should not matter and these short strings should do the same as the long ones (with the difference that AES256 comes before AES128)

Also I don't think there are any browsers that only support TLS 1.1 as the highest protocol and I disabled it on my machines but that is debatable.

**Comment by jvehent** [comment]
Thanks for the report. We need the long ciphersuite to achieve the prioritization described in [1]. A shorter ciphersuite is less optimized for our needs.

Closing this as the current is what we want.

[1] https://wiki.mozilla.org/Security/Server_Side_TLS#Prioritization_logic
