### ISSUE TITLE
Invalid DH param for Java 6

### ISSUE THREAD

**Issue by rafaelmagu** [mozilla/server-side-tls#31]
We've been testing the generator and found that the `tune.ssl.default-dh-param` setting recommendation is incorrect when trying to support Java 6 (the old config). Java 6 has a maximum acceptable size of 1024.

**Comment by nbibler** [comment]
Presumably this would only affect an "old" or perhaps "intermediate" configuration as Java 6 was EOL'd in [February of 2013](http://en.wikipedia.org/wiki/Java_version_history#Java_6_updates).

**Comment by nbibler** [comment]
Strike that, looks like Java 7 is "intermediate" while Java 6 is "old" here.

**Comment by rafaelmagu** [comment]
Indeed, this only applies to the "old" configuration. In this case, "Oldest compatible clients" is incorrect.

![Invalid config](https://www.dropbox.com/s/lmesam0x8isihwk/Screenshot%202015-03-11%2009.11.37.png?dl=1)

**Comment by jvehent** [comment]
Argh, the DH param is hardcoded in the haproxy conf sample. Gotta fix that, thanks for the report!

```
99 global
100     # set default parameters to the {{securityProfile}} configuration
101     tune.ssl.default-dh-param 2048
102     ssl-default-bind-ciphers {{cipherSuites}}
```
