### ISSUE TITLE
Add IfModule mod_headers.c so Apache does not fail to start

### ISSUE THREAD

**Issue by alexhass** [mozilla/server-side-tls#33]
Current:

```
    # HSTS (mod_headers is required) (15768000 seconds = 6 months)
    Header always add Strict-Transport-Security "max-age=15768000"
```

Better:

```
    <IfModule mod_headers.c>
      # HSTS (mod_headers is required) (15768000 seconds = 6 months)
      Header always add Strict-Transport-Security "max-age=15768000"

      # The page can only be displayed in a frame on the same origin as the page itself.
      Header always append X-Frame-Options SAMEORIGIN
    </IfModule>
```

**Comment by jvehent** [comment]
That seems reasonable. Can the `IfModule` statement be placed without a virtualhost without causing errors?

Bonus point if you've got a pull request :+1:

**Comment by lgarron** [comment]
This is your third duplicate issue, @yamlfd. I suggest looking through [closed issues](https://github.com/mozilla/server-side-tls/issues?q=is%3Aissue+is%3Aclosed) before creating a new one. (If you still want to create an issue about something that has been covered before, then you also know what reasons you need to address.)

Here's [the comment I left on issue #15](https://github.com/mozilla/server-side-tls/issues/15#issuecomment-63374277):

> This would cause a silent failure if mod_headers.c is disabled, or if you migrate to a system that doesn't have it. It would appear that everything is still fine (and HSTS would even continue to work for past visitors until it expires!), but the security of the site would drop substantially.
> 
> HSTS is all about hard failures on the client side, and we should encourage similar diligence on the server side. Better to cause annoying errors than to cause surprises for people who _thought_ they were secure. (I'm usually a fan of making things "just work", but you have to be careful with security. And if someone is deploying HSTS, they need to know a bit about what they're getting themselves into.)
> 
> I think the line should be included unconditionally if the HSTS checkbox is checked.

If their server cannot support it, the site operator can always choose not to implement HSTS (there's even a checkbox for it in the config generator!).

**Comment by jvehent** [comment]
Agreed. Closing.

**Comment by alexhass** [comment]
That make sense to me. Why are you not adding a comment? Are you waiting for 4/5 duplicate? :-)
