### ISSUE TITLE
Implement safer intermediate profile

### ISSUE THREAD

**Issue by alexhass** [mozilla/server-side-tls#34]
apache 2.2.22 | intermediate profile | OpenSSL 1.0.1e

This is a much better config than above:
´´´
    SSLProtocol ALL -SSLv2 -SSLv3
    SSLHonorCipherOrder On
    SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
´´´

It uses 256bit ciphers for all modern browsers.

**Comment by lgarron** [comment]
Could you explain why you believe this is safer?

As I commented on [another issue](https://github.com/mozilla/server-side-tls/issues/25#issuecomment-74653396), the recommended cipher list orders based on thoughtful recommendations from a long-standing wiki page, with some accompanying justifications. (And 256-bit ciphers are not really better than 128-bit ciphers.)
