### ISSUE TITLE
Remove 128 bit payload encryption from `modern`

### ISSUE THREAD

**Issue by mikemaccana** [mozilla/server-side-tls#35]
Hi there, I just implemented a [node port of these settings](https://www.npmjs.com/package/ssl-config) and when testing noticed the following:

Since modern is already IE11 / Android 4.4 up, it seems reasonable to get rid of 128 bit payload encryption from the ciphers. The new list would be:

```
[
    "ECDHE-RSA-AES256-GCM-SHA384",
    "ECDHE-ECDSA-AES256-GCM-SHA384",
    "kEDH+AESGCM",
    "ECDHE-RSA-AES256-SHA384",
    "ECDHE-ECDSA-AES256-SHA384",
    "ECDHE-RSA-AES256-SHA",
    "ECDHE-ECDSA-AES256-SHA",
    "DHE-RSA-AES256-SHA256",
    "DHE-DSS-AES256-SHA",
    "DHE-RSA-AES256-SHA",
    "!aNULL",
    "!eNULL",
    "!EXPORT",
    "!DES",
    "!RC4",
    "!3DES",
    "!MD5",
    "!PSK"
].join(':')
```

You wouldn't lose any browser support, and you would increase the strength of the encryption.

**Comment by mikemaccana** [comment]
PS with both #35 and #36 I'm happy to make the changes, just let me know if I'm missing something.

**Comment by Nekit1234007** [comment]
Both [Firefox](https://www.ssllabs.com/ssltest/viewClient.html?name=Firefox&version=35&platform=OS%20X) and [Chrome](https://www.ssllabs.com/ssltest/viewClient.html?name=Chrome&version=40&platform=OS%20X) don't support AES-GCM with 256 keys. And 128-bit keys are [good enough](https://wiki.mozilla.org/Security/Server_Side_TLS#Prioritization_logic) for the time being.

**Comment by lgarron** [comment]
See issues #25 , #32, and #34 for previous refutations of this suggestion.

(EDIT: #25, not #22, as pointed out by @mikemaccana below.)

**Comment by mikemaccana** [comment]
Thanks @Nekit1234007. I'll add a link to the https://wiki.mozilla.org/Security/Server_Side_TLS#Prioritization_logic in the docs for the node port.

@lgarron thanks & acknowledged re: #32 and #32. Not sure where #22 comes into it.

**Comment by mikemaccana** [comment]
@Nekit1234007 re: Firefox and Chrome 'not supporting' AES_256_CBC, do you mean just not prioritising? [Chrome](https://www.ssllabs.com/ssltest/viewClient.html?name=Chrome&version=40&platform=OS%20X) and [Firefox](https://www.ssllabs.com/ssltest/viewClient.html?name=Firefox&version=35&platform=OS%20X) suites include `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA`
