### ISSUE TITLE
Add a modern-intermediate setting for those who have to support IE10/9

### ISSUE THREAD

**Issue by mikemaccana** [mozilla/server-side-tls#36]
`modern` is great, but since IE10 is still around and only does TLS v1, not that many people can use this setting. The next setting is `intermediate`, all the way back to IE7. 

How about a new setting that
- Still sets minimumTLSVersion to `tlsv1` like intermediate
- Start with `cipherSuites` from `modern` (cutting out all 128 bit payloads - see https://github.com/mozilla/server-side-tls/issues/35)

This would be a reasonable step down for people who have to support IE10.

**Comment by mikemaccana** [comment]
Here's the handshaking results of this proposal (browsers out of screenshot all shook without issue).

![screen shot 2015-03-29 at 21 38 54](https://cloud.githubusercontent.com/assets/172594/6887677/d83ab5e4-d65e-11e4-8f17-8f44356da25c.png)

**Comment by gene1wood** [comment]
@jvehent can you weigh in on this notion of a fourth profile?

**Comment by gene1wood** [comment]
So currently IE 7-10, which only support TLS 1.0, represent [11.49%](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0) of the browser market ( 0.99 + 2.17 + 3.25 + 4.79 ). I'm gonna say that the definition/intent of `modern` is explicitly to represent the current state of technology and purposefully support modern browsers only. For support of a more realistic and broad set of browsers, `intermediate` is the way to go.

The notion of adding a fourth level I think would not be worth the complexity. This is a subjective call but I think this holds to the intent of the levels best.
