### ISSUE TITLE
Apache 2.2.3 TLS error

### ISSUE THREAD

**Issue by tony-caffe** [mozilla/server-side-tls#37]
TLSv1 can not be removed on CentOS 5.11 using apache 2.2.3 and OpenSSL 0.9.8e.

See my comment here:
http://unix.stackexchange.com/questions/191302/does-apache-2-2-3-support-tlsv1-1-and-tlsv1-2/195140#195140

**Comment by gene1wood** [comment]
Looks like the addition of TLS v1.1 and v1.2 support in Apache happened at [Revision 1222922](http://svn.apache.org/viewvc?view=revision&revision=1222922) which was then released with [version 2.4.0](http://svn.apache.org/viewvc/httpd/httpd/tags/2.4.0/modules/ssl/ssl_engine_config.c?view=markup)

**Comment by gene1wood** [comment]
@jvehent Looking at Apache prior to 2.4.0 in which support for TLS v1.1 and v1.2 was added, it looks like `SSLv3` and `TLSv1` are the two protocols available. Does this make `modern` and `intermediate` not possible on Apache prior to 2.4.0? Or is there a combination of protocols and ciphersuites that would satisfy `modern` and/or `intermediate` with this protocol constraint?

[SSL config at 2.3.16](http://svn.apache.org/viewvc/httpd/httpd/tags/2.3.16/modules/ssl/ssl_engine_config.c?view=markup)

**Comment by jvehent** [comment]
The intermediate conf accepts TLSv1, so it will work with apache < 2.4.
Modern will not be possible if TLSv1.1 or 1.2 are not supported.
