### ISSUE TITLE
[UI] generator requires me to click off apache and back on to view config

### ISSUE THREAD

**Issue by mikedevita** [mozilla/server-side-tls#38]
In my opinion, the very first thing that should show is the "most common" configuration for apache, or maybe the latest stable version. It was quite confusing to me when visiting the site that I needed to click a radio button and back to apache to view my configs. 

I think the generated configs need to show by default for whatever is set as the pre-filled elements.

I'd be happy to submit a PR for this if needed.
## Steps To Reproduce
1. go to https://mozilla.github.io/server-side-tls/ssl-config-generator/?1
2. configs arent showing using default settings (apache, modern)
3. to make it show, change any field

**Animated GIF of the issue**
## System Info

OS: WIndows 7 x64
Browser: Chrome Version 43.0.2357.2 dev-m (64-bit)

**Comment by gene1wood** [comment]
@mikedevita Interesting. This behavior doesn't happen on my Chrome or Firefox under Ubuntu. Could you try the page in a new profile in your Chrome installation to determine if it relates to your add-ons/extensions or if it's common to all Chrome installations on Windows 7. Could you also try it on Firefox to see if it happens for you there as well?

**Comment by gene1wood** [comment]
Got it, this looks to be related to the PR #23 which introduced permalinks. The issue occurs for this URL

https://mozilla.github.io/server-side-tls/ssl-config-generator/?1

and not this URL

https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by mikedevita** [comment]
Strange when I visited the straight link it was broken like the issue described. I'll look into it

**Comment by gene1wood** [comment]
@mikedevita Do you know how you encountered that link you're using ( https://mozilla.github.io/server-side-tls/ssl-config-generator/?1 ). I'm unsure what caused the `?1`. Is there a page somewhere that links to this invalid parameter?

**Comment by mikedevita** [comment]
It might have been from hacker news.
