### ISSUE TITLE
Feature request: dropdowns for server/libssl versions

### ISSUE THREAD

**Issue by ipartola** [mozilla/server-side-tls#39]
Can openssl version and nginx version be dropdowns? For example, I know I'm on latest stable nginx, but I don't know what exact version number it is. Also it's not obvious that the configuration will change if you update these values.

nginx versions can be pulled from http://nginx.org/en/CHANGES. This does not say which versions are stable or not but it gives a list of code releases.

For OpenSSL, it may be tricker since several branches are maintained. One idea is to use a filtered list of tags as published at https://github.com/openssl/openssl.

For apache2, try https://www.apachelounge.com/Changelog-2.4.html and https://www.apachelounge.com/Changelog.html. 

For HAProxy: https://github.com/haproxy/haproxy/blob/master/CHANGELOG

**Comment by johnkeeping** [comment]
How about providing ranges?

It looks like only a small number of version comparisons are actually performed, so the dropdown could just offer nginx `<0.7.2`, `0.7.2-0.7.13`, `0.7.14-1.3.6` and `1.3.7+`.

**Comment by ipartola** [comment]
I was actually just about to comment with that same thing. If only certain ranges are important and already known, showing options for just those would be great.

**Comment by wickchucked** [comment]
I think it would be very helpful to have drop downs with a list of the the versions however you do it be it a range, or specific, but you could also still include the text box where they could enter the version number like it is now.  Maybe the best of both worlds?

**Comment by gene1wood** [comment]
So PR #53 provides the "best of both worlds" @wickchucked mentioned. This doesn't do ranges as determining what the meaningful ranges, within which no ssl related changes happened, would be difficult. It also doesn't do "latest" as that would also be hard.

This allows you to select from the list or type in an arbitrary version which should accommodate when new web server and openssl versions come out.
