### ISSUE TITLE
Add indicator for age and/or prevalence of compatible clients

### ISSUE THREAD

**Issue by dnnr** [mozilla/server-side-tls#40]
Experienced users might already know exactly which client versions they want to support. For everyone else, it's probably useful to see how old the given client versions are in years and/or to have an estimate of the overall percentage of users that will be covered by the compatible versions.

**Comment by gene1wood** [comment]
Does anyone know where we can get the data of client age and client usage? Any links to studies out there that would provide this data that we could use?

**Comment by gene1wood** [comment]
Looks like [ssl labs](https://api.ssllabs.com/api/v3/getClients) provides data on clients and what they support. If code could be added that consumes this and compares it against the [levels](https://github.com/mozilla/server-side-tls/tree/gh-pages/json) that would get us the first piece, which clients are supported by which levels.

The second piece of client age could be data that someone just assembles from wikipedia and turns into json. Anyone could put this together.

And for the final piece of market share : [netmarketshare](https://www.netmarketshare.com/features.aspx) will provide that data for $300 a month. I guess we could just do point in time manual exports in lieu of subscribing? I don't know.

**Comment by april** [comment]
The newest version of the guidelines mention that Intermediate supports most every client in the last five (up to 10 or so, depending on client) years.
