### ISSUE TITLE
Apache 2 versions 2.3.16 and after don't support SSLv2

### ISSUE THREAD

**Issue by caldwell** [mozilla/server-side-tls#41]
Therefore:

```
    SSLProtocol all -SSLv2
```

is a NOP. It should probably be removed from the file if the Apache version is >= 2.3.16.

**Comment by gene1wood** [comment]
Confirmed that 2.3.16 is the version where it changed. [CHANGES](http://svn.apache.org/viewvc/httpd/httpd/branches/2.4.x/CHANGES?revision=1214787&view=markup) showing the commit from [Revision 1203491](http://svn.apache.org/viewvc?view=revision&revision=1203491)
