### ISSUE TITLE
Add "latest" option to server version

### ISSUE THREAD

**Issue by kofalt** [mozilla/server-side-tls#43]
It wasn't immediately obvious to me that I could change the requested nginx version to, say, [99](https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-99&openssl=0.9.8h&hsts=yes&profile=modern) and additionally receive OCSP stapling directives.

It would be nice to allow the string "latest" to return the most modern instructions available, and possibly default to that setting.

**Comment by kofalt** [comment]
Related to #39

**Comment by april** [comment]
The newest generator tracks the newest versions of each software, and overall handles this a lot better:
https://ssl-config.mozilla.org/
