### ISSUE TITLE
lighttpd support

### ISSUE THREAD

**Issue by mhspace** [mozilla/server-side-tls#45]

**Comment by gene1wood** [comment]
@mhspace (or anyone else) if you have sample configs they can provide for lighthttpd showing the different ciphersuites and tls versions I'd be happy to add it in as a supported webserver.

**Comment by Gillingham** [comment]
@gene1wood 

Mostly taken from http://redmine.lighttpd.net/projects/1/wiki/docs_ssl#Configuration

```
ssl.engine = "enable" 
ssl.pemfile = "/path/to/private_key_plus_signed_certificate" 
ssl.ca-file = "/path/to/intermediate_certificate"
ssl.cipher-list = "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA "
ssl.dh-file = "/path/to/dhparam.pem"
```

To toggle ssl2/3 support:
ssl.use-sslv2   enable/disable use of SSL version 2 (lighttpd < 1.4.21 only, newer version don't support SSLv2)
ssl.use-sslv3   enable/disable use of SSL version 3 (lighttpd >= 1.4.29 only)
example: `ssl.use-sslv3 = "disable"`

**Comment by april** [comment]
lighttpd is fully supported in the new version of the generator:
https://ssl-config.mozilla.org/
