### ISSUE TITLE
Explain how to generate dhparam

### ISSUE THREAD

**Issue by thefinn93** [mozilla/server-side-tls#48]
Both the nginx and HAProxy configs include a path to a `dhparam.pem`, but there is no explanation for how to generate it. Googling indicates it's pretty simple (`openssl dhparam -out /path/to/dhparam.pem 2048`) but it requires an extra search that seems like it shouldn't be needed. I suggest adding a comment above the line that mentions it indicating how to generate it.

**Comment by jvehent** [comment]
A number of servers provide default parameters out of the box, but we could link to the wiki page https://wiki.mozilla.org/Security/Server_Side_TLS#DHE_handshake_and_dhparam

**Comment by gene1wood** [comment]
@jvehent What do you recommend? Should we add a comment to the nginx and haproxy configs pointing to that wiki link? Should we add instructions on how to generate a dhparam file to the wiki and add a comment to the config linking to it? Something else?

**Comment by jvehent** [comment]
I'd recommend linking to the wiki for knowledge dissemination. The command is simple, but understanding how the DHE parameter is used warrants some explanations that the wiki already has.

**Comment by ghost** [comment]
@jvehent @gene1wood Could we leave this as a Good First Bug and have @thefinn93 submit a pull request should he be interested?

**Comment by gene1wood** [comment]
@bkerensa Sure.
@thefinn93 comment here if that sounds good. If not or if I don't hear from you I'll take care of it.

**Comment by thefinn93** [comment]
I'm not entirely sure how to add/test that, I guess just edit [this line](https://github.com/mozilla/server-side-tls/blob/gh-pages/ssl-config-generator/index.html#L273)?

**Comment by gene1wood** [comment]
@thefinn93 Looks like what @jvehent suggested was to add a comment in the produced config file that is a link to the wiki page describing more information about dhparam. Do probably you'll want to edit the config payload for haproxy

**Comment by thefinn93** [comment]
Alright, I assume the nginx payload too? That line I linked seems to be more nginx specific, didn't realize it was in the HA Proxy payload

**Comment by jvehent** [comment]
I'm not sure about nginx, but haproxy will generate a diffie hellman parameter on its own when `tune.ssl.default-dh-param` is set. So, is it really necessary to point people to manual instructions when the tool takes care of that for you?

**Comment by thefinn93** [comment]
nginx will not do that, hence this thread. I have no idea about haproxy. Should I remove the comment from the HA Proxy config?

**Comment by nbibler** [comment]
I believe nginx currently generates a dhparam file with OpenSSL's default configuration (a 1024 bit key). If you'd like a stronger key file, you have to manually generate it as described above.

As an aside, "old" configurations (Java 6) do not support DH > 1024. Presumably that's not a concern here, though.

**Comment by april** [comment]
The new generator either points to RFC 7919 ffdhe2048 (for Intermediate) or includes instructions for Old (using dhparams).

https://ssl-config.mozilla.org/
