### ISSUE TITLE
OCSP stapling in haproxy

### ISSUE THREAD

**Issue by pierreozoux** [mozilla/server-side-tls#51]
I was looking for OCSP stapling in HAproxy, and it is quiet difficult to achieve.

I added that to the mozilla wiki: https://wiki.mozilla.org/Talk:Security/Server_Side_TLS#OCSP_in_HAProxy

I was wondering how we could add it to this website? It is nice information to have. And even if it is a hacky bach script, I'd love to have feedback from people!

Thanks!

**Comment by jvehent** [comment]
I replied there directly because it's an addition that should be made to the wiki page first.
https://wiki.mozilla.org/Talk:Security/Server_Side_TLS#reply_from_ulfr.2C_20150415
For this tool, a link to the wiki would be better than providing the whole script in the generator.

**Comment by pierreozoux** [comment]
thanks for your reply :)
what needs to be done to go further on the wiki part?
Then we could add a comment in the haproxy configuration pointing to the wiki.

**Comment by april** [comment]
If you can figure out an easy way to do this in the configuration generator, I'd love to add it:
https://github.com/mozilla/ssl-config-generator

But the way it seems to work seems a lot more complicated than Apache/nginx. Thanks!
