### ISSUE TITLE
Apache config fails `which apache2ctl` -V due to "..."

### ISSUE THREAD

**Issue by clintwilson** [mozilla/server-side-tls#59]
If the generated Apache VirtualHost is copied directly in Apache 2.4.7, Apache2 will fail to load.

Running `which apache2ctl` -V or apachectl configtest or trying to restart Apache will fail:

AH00526: Syntax error on line [x] of /etc/apache2/sites-enabled/default-ssl.conf:
Invalid command '...', perhaps misspelled or defined by a module not included in the server configuration

The "..." at the beginning and end of the VirtualHost cause syntax errors on Apache 2.4.7. Even though this is just a "guideline" for setting up the VirtualHost, it seems these lines are unnecessary. I imagine the syntax error would occur on other versions as well, but I have not tested.

**Comment by jvehent** [comment]
I would think that this is a decent safeguard against blind copy/paste. My personal take on it is that people should use the tool but also _understand_ what the tool does. So I'd be inclined to leave these three dots in place, but it's @gene1wood 's call.

**Comment by clintwilson** [comment]
Even if the three dots are removed, the config still won't work without other changes to it, but I do agree that the tool should be understood by its users. 
As long as it's a conscientious choice with thought behind putting them in, then I can accept it going either way.

**Comment by gene1wood** [comment]
@clintwilson I've actually been meaning to make the exact change you're suggesting. @jvehent I agree that the output should require the user understand it a bit, but I think we're safe as all the paths to the certs are invalid. I like the idea of having a lexically valid config so I'll make this change to get the configs to validate.

**Comment by april** [comment]
This has been fixed in the newest version of the generator, where the various pieces of software were inconsistent about it anyways:

https://ssl-config.mozilla.org/
