### ISSUE TITLE
nginx 1.6.x missing from autocomplete list

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/server-side-tls#60]
Could it be that the entire 1.6.x series are missing from Javascript?

**Comment by ian-kelling** [comment]
Yes, the version completion list is missing the 1.6 series for me as well. It doesn't mean it's not supported, but this should be fixed.

**Comment by gene1wood** [comment]
The version list in the autocomplete which was added in PR #53 was derived from the versions enumerated in the Nginx changelog : http://nginx.org/en/CHANGES

It appears that 1.6 has it's own changelog for some reason? : http://nginx.org/en/CHANGES-1.6

Any idea what's going on here or what I should use as an authoritative list of nginx versions?

**Comment by ian-kelling** [comment]
I see what's going on. 1.6 is a "stable branch", developed alongside other branches. So for the changelog to be an accurate history of the main branch, it must exclude at least stable branch changes which aren't in main, which means the stable branch needs it's own changelog. So the authoritative list of versions is the union of versions in http://nginx.org/en/CHANGES and  http://nginx.org/en/CHANGES-0.6, 0.8, 1.0, ... 1.8

**Comment by gene1wood** [comment]
Ok, based on the [list of change files](trac.nginx.org/nginx/browser/nginx_org/text/en) I'll grab the versions like this

```
for branch in "" -0.5 -0.6 -0.7 -0.8 -1.0 -1.2 -1.4 -1.6 -1.8; do curl -s "http://nginx.org/en/CHANGES${branch}" | awk '$1 == "Changes" && $2 == "with" && $3 == "nginx" {print $4}'; done | sort --version-sort | uniq
```

and update the list

**Comment by szepeviktor** [comment]
Thank you.
