### ISSUE TITLE
Profile for Apache 2.2.15 with OpenSSL 0.9.8f is broken (running on SUSE Linux Enterprise 11 SP 3)

### ISSUE THREAD

**Issue by anderstn** [mozilla/server-side-tls#61]
Hi

The profile for Apache 2.2.15 with OpenSSL 0.9.8f running on SUSE Linux Enterprise 11 SP 3 is broken. Using some experimentation i managed to establish that the following CipherSuites breaks the config:
KRB5-DES-CBC3-SHA, aECDH, AES and anything using the SHA384 algorithm.

If this is spesific to the apache/openssl package(s) included with the distro it might be wise to include a footnote on the page or pherhaps a drop down distro selector.

Either way thanks for a great little tool ;)

**Comment by jvehent** [comment]
I'm not sure it would be wise to accomodate edge cases from distributions in this tool. The management overhead is quite large. But I would definitely recommend that you file a bug with the SUSE support to get it fixed. SHA384 is quite important!
