### ISSUE TITLE
Apache 2.2 does support TLS v1.1 and v1.2

### ISSUE THREAD

**Issue by brd** [mozilla/server-side-tls#62]
The mouse over for a modern config with Apache 2.2 says that TLS v1.1 & v1.2 is only supported in Apache 2.4.

The docs for Apache 2.2 reflect this support here: https://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslprotocol

**Comment by gene1wood** [comment]
Hmm, odd. I went and looked [here](https://github.com/mozilla/server-side-tls/issues/37#issuecomment-92546031) for the commit in which support was added and it looks like it came out in 2.4. @brd have you tested enabling TLS v1.1 & 1.2 in Apache 2.2? If so what did you find and what was the exact version and ideally package version as well?

**Comment by brd** [comment]
It was added in Apache 2.2.23.. See http://www.apache.org/dist/httpd/CHANGES_2.2

**Comment by davidfuhr** [comment]
I can confirm that TLSv1.1 and TLSv1.2 are available on Apache 2.2.24 with openssl 1.0.1.

**Comment by cernicka** [comment]
Debian 7 Wheezy includes Apache 2.2.22 with TLS 1.2 backported since 30th July 2012.
Reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=682897

**Comment by Gillingham** [comment]
Not sure what this issue is reporting, I think it can be closed?
I generated a config for 2.2.29 and it spat out "SSLProtocol             all -SSLv2 -SSLv3"
Which enables TLS 1.(0|1|2) just fine.

**Comment by brd** [comment]
No, it can't be closed.
The tip doesn't say you can enable TLS 1.2 in Apache 2.2.x

**Comment by sugoiyo** [comment]
We're still using the older Apache 2.2.15 on https://www.fashion.net/, but managed to tweak our configuration to get an A+ on SSL Labs, and Google's Chrome browser reports:

Your connection to www.fashion.net is encrypted using a modern cipher suite.
The connection uses TLS 1.2.
The connection is encrypted and authenticated using AES_128_GCM and uses ECDHE_RSA as the key exchange mechanism.

Our configuration is:

Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
SSLEngine on
SSLProtocol all -SSLv3 -SSLv2
SSLHonorCipherOrder On
SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA

Looking for the installed versions of Apache and OpenSSL, we got:

apachectl -V

Server version: Apache/2.2.15 (Unix)
Server built: Aug 15 2014 03:02:07
Server's Module Magic Number: 20051115:25
Server loaded: APR 1.3.9, APR-Util 1.3.9
Compiled using: APR 1.3.9, APR-Util 1.3.9
Architecture: 64-bit
Server MPM: Prefork
threaded: no
forked: yes (variable process count)
Server compiled with....
-D APACHE_MPM_DIR="server/mpm/prefork"
-D APR_HAS_SENDFILE
-D APR_HAS_MMAP
-D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
-D APR_USE_SYSVSEM_SERIALIZE
-D APR_USE_PTHREAD_SERIALIZE
-D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
-D APR_HAS_OTHER_CHILD
-D AP_HAVE_RELIABLE_PIPED_LOGS
-D DYNAMIC_MODULE_LIMIT=128
-D HTTPD_ROOT="/etc/httpd"
-D SUEXEC_BIN="/usr/sbin/suexec"
-D DEFAULT_PIDLOG="run/httpd.pid"
-D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
-D DEFAULT_LOCKFILE="logs/accept.lock"
-D DEFAULT_ERRORLOG="logs/error_log"
-D AP_TYPES_CONFIG_FILE="conf/mime.types"
-D SERVER_CONFIG_FILE="conf/httpd.conf"

openssl version

OpenSSL 1.0.1e-fips 11 Feb 2013
