### ISSUE TITLE
Apache profiles: Missing config for custom DH parameter file

### ISSUE THREAD

**Issue by bugdebugger** [mozilla/server-side-tls#67]
The nginx and HAProxy profiles include config statements for custom DH parameters.
Apache also supports custom DH parameters.

**Version requirements**
- Apache >= 2.4.8
- OpenSSL used for mod_ssl >= 1.0.2

`SSLOpenSSLConfCmd DHParameters "/path/to/custom/dhparams.pem"`

If this it added it should, similar to the comment in the nginx profile, include a comment with recommended DH key size based on the chosen profile.

Apache documentation: http://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslopensslconfcmd

Related to mozilla/server-side-tls/issues/48 and mozilla/server-side-tls/issues/66

**Comment by bbaetz** [comment]
Apache also supports loading dhparams put at the end of the certificate file, from v2.4.7 - see http://httpd.apache.org/docs/2.4/ssl/ssl_faq.html#javadh

Support for this was backported to some vendor 2.2 apache (eg RHEL6) along with support for >1024 bit params

**Comment by april** [comment]
The new generator now accounts for this.  :)
