### ISSUE TITLE
Logjam - disable weak DHE ciphers

### ISSUE THREAD

**Issue by cernicka** [mozilla/server-side-tls#68]
It seems to me that the weak DHE ciphers should be disabled. E.g. for apache2 on Debian 7 Wheezy with openssl 1.0.1e, all the ciphers starting with DHE must be explicitly disabled by adding this to the line SSLCipherSuite:

!DHE-DSS-AES256-GCM-SHA384:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES256-SHA256:!DHE-DSS-AES256-SHA256:!DHE-RSA-AES256-SHA:!DHE-DSS-AES256-SHA:!DHE-RSA-CAMELLIA256-SHA:!DHE-DSS-CAMELLIA256-SHA:!DHE-DSS-AES128-GCM-SHA256:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES128-SHA256:!DHE-DSS-AES128-SHA256:!DHE-RSA-AES128-SHA:!DHE-DSS-AES128-SHA:!DHE-RSA-SEED-SHA:!DHE-DSS-SEED-SHA:!DHE-RSA-CAMELLIA128-SHA:!DHE-DSS-CAMELLIA128-SHA

Only after having all these in, the test on ssllabs.com grants the highest score.

Please someone correct me if I misunderstood it.

**Comment by MarcoRemy** [comment]
I'm running a similar machine and can confirm this. Please Remove the weak DHE cyphers from the generator.

**Comment by tomato42** [comment]
RHEL6's and CentOS 6 version of mod_ssl will select appropriate DH parameters automatically - if you have 2048 bit RSA key it will use 2048 bit DH parameters.

that gives me an A+ from ssllabs (not that Server Side SSL goal is to get high score on ssllabs...)

**Comment by april** [comment]
This is done in the newest version of the generator:
https://github.com/mozilla/ssl-config-generator
