### ISSUE TITLE
AES256 should be preferred to AES128.

### ISSUE THREAD

**Issue by clopez** [mozilla/server-side-tls#72]
First of all: I'm not a cryptographer

But my understanding is that AES256 is more secure than AES128 and it should be preferred on the list of ciphers.

Before you point me to http://eprint.iacr.org/2009/374 take into account that such attack is a related-key attack, and therefore requires ""the cryptanalyst to have access to plaintexts encrypted with multiple keys that are related in a specific way"".   [Quote from: https://www.schneier.com/blog/archives/2009/07/another_new_aes.html ]

So my understanding is that such attack is not possible in a well designed cryptographic system. Therefore AES256 should provide better security than AES128 in real applications, and it is a saner default for the next years. Read for example this interesting article about the NSA recommending AES256 for top-secret material because of hypothetical future attacks using quantum computers: https://blog.agilebits.com/2013/03/09/guess-why-were-moving-to-256-bit-aes-keys/

So, any reason to recommend AES128 instead of AES256? I think that the ciphers with AES256 should be preferred to the ones with AES128.

**Comment by lgarron** [comment]
See issues #25, #32, #34, and #35 for previous refutations.

**Comment by clopez** [comment]
Thanks for the pointers. It was very interesting to know that Chrome developers want to ditch AES-256 ciphers or that both Firefox and Chrome actually prefer AES-128.

I have also opened a parallel discussion at http://www.reddit.com/r/crypto/comments/39211m/is_really_aes256_less_secure_than_aes128/ which has some interesting comments.

After reading all the opinions on the matter I agree that AES-128 is a a good trade-off, since is faster (~30%) and provides more than enough security.
