### ISSUE TITLE
IE 7 or 8 ?

### ISSUE THREAD

**Issue by asaladin** [mozilla/server-side-tls#77]
Hi,

The list of compatible browsers is not clear. The "intermediate" configuration for nginx mentions:
Oldest compatible clients : Firefox 1, Chrome 1, **IE 7**, Opera 5, Safari 1, Windows XP **IE8**, Android 2.3, Java 7

Which IE is the correct one ?

https://github.com/mozilla/server-side-tls/blob/gh-pages/ssl-config-generator/index.html#L205

**Comment by realityking** [comment]
According to the wiki (https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29) it would be IE7. Hoewever it may be that IE7 on Windows XP is unsupported but IE8 on Windows XP works.

**Comment by april** [comment]
The newer generator and guidelines are a lot clearer on this.  :)
