### ISSUE TITLE
Add support for Tomcat 7 + 8

### ISSUE THREAD

**Issue by fusrodave** [mozilla/server-side-tls#82]
Tomcat is not a currently listed server, so there is no profile for a HTTPS connector. Would be great to have one added so Coyote can be used to serve HTTPS in a modern, secure manner.

**Comment by jvehent** [comment]
I know for certain we never terminate HTTPS on anything java at Mozilla, so I'm afraid I don't have code to contribute. Do you have anything?

**Comment by gene1wood** [comment]
Ya, @cuzzasoft a PR is welcome for Tomcat

**Comment by jauderho** [comment]
This is somewhat difficult given that there are different Java versions that can plug into different versions of Tomcat. Further complicating the issue is minor revisions of Tomcat have steadily added additional features such as XFO etc.

How would that be handled?

I do have some notes on possible combinations that I'm happy to add but it's only for Tomcat 7 + Java 7 at this time.

**Comment by stevespringett** [comment]
I'm also interested in this subject, but I don't think there will be all that many combinations if we only concentrate on Java versions that are not end of life (currently only Java 1.8), and the latest Tomcat release + point release (currently only Tomcat 8.0 and 8.5).

**Comment by stevespringett** [comment]
The following config unveils the green lock in Chrome. This config is Tomcat-specific and works with Tomcat 8 on Java 8. This config does not specify precisely what ciphers to use.

tomcat/conf/server.xml

``` xml
<Connector port="8080" protocol="HTTP/1.1"
    connectionTimeout="20000"
    redirectPort="443" />

<Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
    maxThreads="150" SSLEnabled="true" scheme="https" secure="true"
    clientAuth="false" sslProtocol="TLS" sslEnabledProtocols="TLSv1.2" 
    keystoreFile="/path/to/keystore.jks" keyAlias="server" keystorePass="jkspassword"/>
```

tomcat/conf/web.xml

``` xml
<filter>
    <filter-name>httpHeaderSecurity</filter-name>
    <filter-class>org.apache.catalina.filters.HttpHeaderSecurityFilter</filter-class>
    <init-param>
        <param-name>hstsEnabled</param-name>
        <param-value>true</param-value>
    </init-param>
    <init-param>
        <param-name>hstsMaxAgeSeconds</param-name>
        <param-value>31536000</param-value>
    </init-param>
    <init-param>
        <param-name>hstsIncludeSubDomains</param-name>
        <param-value>false</param-value>
    </init-param>
    <async-supported>true</async-supported>
</filter>

<filter-mapping>
    <filter-name>httpHeaderSecurity</filter-name>
    <url-pattern>/*</url-pattern>
    <dispatcher>REQUEST</dispatcher>
</filter-mapping>

<security-constraint>
    <web-resource-collection>
        <web-resource-name>Protected Context</web-resource-name>
        <url-pattern>/*</url-pattern>
    </web-resource-collection>
    <user-data-constraint>
        <transport-guarantee>CONFIDENTIAL</transport-guarantee>
    </user-data-constraint>
</security-constraint>
```

**Comment by tomato42** [comment]
you can set the enabled ciphers in Tomcat using the `ciphers` field in `connector`

**Comment by lapo-luchini** [comment]
On Apache Tomcat I'd suggest using [APR Native Connector](https://tomcat.apache.org/tomcat-8.0-doc/config/http.html#SSL_Support_-_APR/Native) which is faster (and has more features) and is decoupled on Java version as it uses OpenSSL and is configured depending only on openssl version, with a variation of the very configuration we already generating from Apache httpd, but using tags, e.g.:

```xml
<Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
<Service name="Catalina">
    <Connector
	protocol="org.apache.coyote.http11.Http11AprProtocol"
	port="8443" maxThreads="200"
	scheme="https" secure="true" SSLEnabled="true"
	SSLCertificateFile="/usr/local/ssl/server.crt"
	SSLCertificateKeyFile="/usr/local/ssl/server.pem"
	SSLHonorCipherOrder="on"
	SSLCipherSuite="ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
	SSLVerifyClient="optional" SSLProtocol="TLSv1+TLSv1.1+TLSv1.2"/>
</Service>
```

**Comment by april** [comment]
If you'd be willing to open up a PR for this over here, I'd be happy to accept it:
https://github.com/mozilla/ssl-config-generator

Thanks!
