### ISSUE TITLE
Version of Nginx is "2.2.15" regardless of toggle

### ISSUE THREAD

**Issue by kennwhite** [mozilla/server-side-tls#86]
On Chrome, it looks like all the profiles for nginx carry over the apache version. Depending on the distro the definition "old" is quite varied: on CentOS 6.7 epel, yum installs v. 1.0.15, and Amazon Linux is currently at 1.6.2. Since many (most?) nginx deployments are probably from source or upstream packages, suggest maybe 1.0, 1.6.2, 1.8?

**Comment by april** [comment]
This is fixed in the newest version of the generator:

https://mozilla.github.io/ssl-config-generator/
