### ISSUE TITLE
Include a redirect from HTTP to HTTPS

### ISSUE THREAD

**Issue by jyasskin** [mozilla/server-side-tls#87]
In the HSTS modes, at least, it'd be nice if the server configuration also included a redirect from HTTP to HTTPS.

**Comment by kofalt** [comment]
:+1:

**Comment by Mikaela** [comment]
:+1:, I would also add `includeSubDomains` as that is the second missing requirement from the [HSTS Preload list](https://hstspreload.appspot.com/). `preload` itself might not hurt either.

**Comment by lgarron** [comment]
> preload itself might not hurt either.

I would recommend against this. Site operators should preload when they _know_ they are ready. It's less risky for new sites, but it's a strong step.

At https://hstspreload.appspot.com/ , we accept _any_ submissions of domains that send the `preload` token, under the assumption that the site operator explicitly wants to opt into preloading. We should not encourage site operators to put this token into their HTTPS configurations blindly (although it would be great to let them know about it).

**Comment by nbibler** [comment]
Agreed with @lgarron.

Also, `includeSubDomains` is not a configuration to take lightly. While the direction is to encrypt all the things, as a community we're not there yet. That one minor configuration change impacts not just one project or site, but potentially many across many development teams. It's something to be cautious with.

**Comment by jvehent** [comment]
As others have said, mistakenly setting `includeSubDomains` on a root domain can have dramatic consequences to a business. But it's also beyond the scope of this tool.

The goal of the configuration samples we provide are not to enforce web application logics, but to help set good security parameters. Redirecting a page from http to https, or forcing https on an entire subdomain, is something that very much depends on the website and business logic around it. We will not add it to the configuration generator.

**Comment by jyasskin** [comment]
You've already added HSTS, which depends on the website and the business logic around it. Why is the redirect that makes HSTS useful more drastic than that?
