### ISSUE TITLE
On (at least) OSX, curl 7.28 was the first version to support TLS 1.1

### ISSUE THREAD

**Issue by jpluscplusm** [mozilla/server-side-tls#92]
The modern profile doesn't allow client access from curl (on OSX) pre-7.28, as that version was the first to introduce TLS 1.1 (and 1.2) support.

This might be worth mentioning in the "Oldest compatible clients" section of the generator.

**Comment by april** [comment]
If you want to do the grindy work to figure out what versions of curl support the various configurations, I'd be happy to include them in the guidelines. But it's pretty hard to figure out, and I'm not sure it's that important now given that almost every `curl` around supports TLS 1.2.
