### ISSUE TITLE
DH params for Apache 2.2.30+

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/server-side-tls#93]
Could you rename `/path/to/signed_certificate_followed_by_intermediate_certs` by mentioning DH params should be appended?
https://github.com/mozilla/server-side-tls/blob/808c316eed8d317d1d7152c2779f487897741cb6/ssl-config-generator/index.html#L312

It is supported from 2.2.30:
http://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslcertificatefile

**Comment by szepeviktor** [comment]
Qualys gives you a lower score because of common DH keys.

**Comment by april** [comment]
I didn't fix this for 2.2.30 because it's deprecated and unmaintained and I didn't want infinite ifdefs, but it should be fixed for Apache 2.4 in the latest version of the certificate generator:

https://mozilla.github.io/ssl-config-generator/#server=apache&server-version=2.4.39&config=intermediate&openssl-version=1.1.1b&hsts=true&ocsp=true

**Comment by gene1wood** [comment]
RHEL 6 and RHEL variants, which is supported through next year is on Apache 2.2.15. We should make sure to not only support currently supported versions of web servers in the generator but also versions which are supported in currently supported major OSs.

**Comment by tomato42** [comment]
Technically, RHEL-6 support will end in 2024 at the earliest[1], but for CentOS-6 and similar, yes, the support ends in November 2020.

 1- RHEL-5 is still supported, but it doesn't include support for TLS 1.2 in Apache so it is of limited importance for this guide

**Comment by april** [comment]
While all this is true, RedHat Enterprise Linux is based off of 2.2.3 (for RHEL 5) and 2.2.15 (for RHEL 6). openSUSE uses earlier versions as well. None of which support custom DH parameters.

This complicates the templates quite a lot to simply add a comment for the set of users that is basically using a manually installed, unsupported, insecure version of Apache.

**Comment by floatingatoll** [comment]
RedHat says they backported DH params to their 2.2.15 branch as of -39, if
I read this right:

https://access.redhat.com/articles/1462193

**Comment by april** [comment]
That's good to know, but even there there isn't much I can do simply because I would break all the 2.2.15+ installations that don't support dhparams. 🤷‍♀️

**Comment by tomato42** [comment]
yeah, asking to map features backported in the myriad of different distributions would be too much – I just meant it as an argument for keeping support for the base version, even if it is unsupported by upstream
