### ISSUE TITLE
server-side-tls version

### ISSUE THREAD

**Issue by szepeviktor** [mozilla/server-side-tls#96]
Please consider indicating server-side-tls version on the Generator page with small letters.

**Comment by szepeviktor** [comment]
Do we have a version??

**Comment by szepeviktor** [comment]
Then at least latest commit date/hash.
https://github.com/mozilla/server-side-tls/commits/gh-pages/ssl-config-generator/index.html

**Comment by april** [comment]
While we don't do that, we now indicate when the configuration was generated so you can easily see if you need a new one.  :)

**Comment by szepeviktor** [comment]
Thank you.
