### ISSUE TITLE
SSLSessionTickets not supported in Apache < 2.4.11

### ISSUE THREAD

**Issue by steffann** [mozilla/server-side-tls#99]
The generator outputs the `SSLSessionTickets` option even for Apache versions that don't support it.

Apache manual:
http://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslsessiontickets

Example generating bad config:
https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.7&openssl=1.0.1f

**Comment by jvehent** [comment]
FIxed in #98
